### ISSUE TITLE
How to change download drive blockchain

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoins** [ZcashFoundation/zecwallet#123]
Is it possible to change the downloaddrive for the blockchain files...something like is possible in bitcoin-qt...
![zcash](https://user-images.githubusercontent.com/45945164/55668891-4fce1c80-5870-11e9-982f-73bfc4114465.PNG)

**Comment by garethtdavies** [comment]
See this: https://docs.zecwallet.co/faq/#can-i-change-the-location-of-the-data-directory

**Comment by SatoshiNakamotoBitcoins** [comment]
@garethtdavies Thnx...mate
