### ISSUE TITLE
Is there a possibility to download the blockchain at once

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoins** [ZcashFoundation/zecwallet#124]
Is there a link where I can download the blockchain at once...syncing with nodes is very slow...

**Comment by adityapk00** [comment]
Unfortunately, this is not supported, since it would centralize the blockchain. 

If you have trouble syncing, please see our docs:
https://docs.zecwallet.co/troubleshooting/#my-node-isnt-syncing-or-is-slow-to-sync

**Comment by SatoshiNakamotoBitcoins** [comment]
@adityapk00 Thnx for your answer!
