### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by Flegy33** [ZcashFoundation/zecwallet#126]
Why it shows only a few transactions not all transactions?

![image](https://user-images.githubusercontent.com/2219344/56835488-a8437900-6874-11e9-8e21-b142dc2363dd.png)

**Comment by adityapk00** [comment]
The reason this happens is that zcashd, the underlying node, doesn't actually store the shielded transactions for various reasons. So, you'll only see a partial history here (only transparent transactions). 

ZecWallet stores shielded transactions in a local store, but it only stores the ones that have been sent from ZecWallet. It can't know transactions that have been sent from elsewhere. 

I know this is not an ideal situation, but we're working towards a better solution, hopefully soon.
