### ISSUE TITLE
stand alone apk

### ISSUE THREAD

**Issue by jrvns** [ZcashFoundation/zecwallet#129]
add the stand alone android apk for not revealing our identity to the play store

**Comment by adityapk00** [comment]
The standalone APKs are available on the project's releases page.
https://github.com/adityapk00/zqwandroid/releases

**Comment by jrvns** [comment]
Hi, 
Please see the attached pics when I'm trying to send some zec. 
Somehow I'm always getting an error. 

On 9 May 2019 17:13:06 GMT+02:00, adityapk00 <notifications@github.com> wrote:
>The standalone APKs are available on the project's releases page.
>https://github.com/adityapk00/zqwandroid/releases

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adityapk00** [comment]
It looks like the pics didn't attach. Can you please upload them again?

**Comment by jrvns** [comment]
Hi,

I made sure the wallet was synced. Also, my phone and laptop were on the 
same network.

Thank you.
