### ISSUE TITLE
Error when starting wallet at MAC

### ISSUE THREAD

**Issue by AlekseiSmirnov** [ZcashFoundation/zecwallet#133]
Just downloaded the latest version of the wallet in order to test private transactions. Couldn't make it work. After the launch application shows an error:

zcashd said: 

************************
EXCEPTION: St13runtime_error       
Assertion failed.       
Zcash in AppInit()       

MacOs Mojave 10.14.4

**Comment by adityapk00** [comment]
Thanks for filing this issue. I'll be away from my Mac, so I'll look into it on Monday. 

In the meanwhile, you can try an older version to see if that works: I'd recommend 0.6.8:
https://github.com/ZcashFoundation/zecwallet/releases/tag/0.6.8

**Comment by AlekseiSmirnov** [comment]
I'm getting the same exception at 0.6.8

**Comment by adityapk00** [comment]
Unfortunately I'm having trouble re producing this issue. Could you maybe post a screenshot? I tried on both MacOS 10.14.4 and 10.14.5

Are you getting the error from ZecWallet or zcashd? Does it work if you run the ZecWallet externally? Is this the first time you're running ZecWallet or zcashd? Do you have a previous installation or download of the zcash blockchain?
