### ISSUE TITLE
Zec wallet donation

### ISSUE THREAD

**Issue by 1tron** [ZcashFoundation/zecwallet#134]
I accidentally donated 744 ZEC to this address: ZecWallet donation/zs1gv64eu0v2wx7raxqxlmj354y9ycznwaau9kduljzczxztvs4qcl00kn2sjxtejvrxnkucw5xx9u
I hope that you can return it to me.
My contact email:tronlink@outlook.com

**Comment by adityapk00** [comment]
Follow up on email
