### ISSUE TITLE
Dark mode/theme

### ISSUE THREAD

**Issue by leto** [ZcashFoundation/zecwallet#136]
ZecWallet is great!

Would it be possible to have a "dark" theme/mode ? That would make it even more awesome.

**Comment by adityapk00** [comment]
Thanks for using ZecWallet!

I looked at the dark mode a while ago, and Qt didn't have good support for it. But since then, they've released new versions, so maybe its time for me to revisit!

I'll look into it this weekend!

**Comment by rex4539** [comment]
+1 for dark mode.

**Comment by Fair-Exchange** [comment]
This has been solved due to fantastic work by @Miodragpops and @Oleksandrblack for the Safecoin project.  PR forthcoming tonight.

**Comment by adityapk00** [comment]
In 0.7.9
