### ISSUE TITLE
importing private key still does not work

### ISSUE THREAD

**Issue by lixujasonFengXing** [ZcashFoundation/zecwallet#137]
after importing a private key with zecwallet version 0.6.11, the imported address did not show. waiting for 4 hours but the imported address still did not show. "zcashd -rescan" command line worked, and it only took less than one hour.

**Comment by adityapk00** [comment]
Yes, the problem is that there is no way for ZecWallet to keep track of the rescan process (It is not available in the RPC calls), so we don't know when the rescan is finished/failed, so we can't update the UI properly. 

Maybe I should add a custom RPC call. 

I'll look into this.

**Comment by leto** [comment]
@adityapk00 it's not a great solution, but looking for `progress=...` in debug.log every X seconds might work

**Comment by adityapk00** [comment]
Actually, the Ycash people are working on a new RPC API to get a rescan status.
https://github.com/ycashfoundation/ycash/compare/master...ycashfoundation:rescan?expand=1

I'm waiting for them to merge it, and I'll add it to ZecWallet

**Comment by adityapk00** [comment]
Closing as stale
