### ISSUE TITLE
View address on explorer

### ISSUE THREAD

**Issue by leto** [ZcashFoundation/zecwallet#138]
When right clicking on addresses on the Balance screen, there are various convenient options already! :+1:

Another potentially useful option would be "view this address on explorer"

**Comment by adityapk00** [comment]
It should already work for t-addresses on the main balances screen. Is it not working for you? Or did I misunderstand it?

![image](https://user-images.githubusercontent.com/31996805/58743549-6a43f280-83e8-11e9-9a73-ec5812c17d80.png)

**Comment by leto** [comment]
@adityapk00 sorry about that! I only right clicked on a zaddr, I see it on a transparent address now. Thanks :+1:
