### ISSUE TITLE
Migration turnstile checkbox deselecting

### ISSUE THREAD

**Issue by garethtdavies** [ZcashFoundation/zecwallet#139]
While updating the docs for the new Sapling turnstile I noticed that you can unselect the "Sprout->Sapling migration enabled" checkbox but this has no effect and `migration=1` remains in zcash.conf. 

Unselecting this box it should remove this line from zcash.conf and then reopen the app.

**Comment by adityapk00** [comment]
Oh, wow. I didn't even realize you can set `migration=1` in the conf file. 

ZecWallet is using the RPC call exclusively. I'll look into incorporating the conf file as well.

**Comment by garethtdavies** [comment]
Ah, OK that makes sense as I already had this set before starting ZecWallet 😕

**Comment by garethtdavies** [comment]
I'm not sure you need to do anything here. It's an edge case and I added a line in the docs to cover it.

**Comment by adityapk00** [comment]
Yeah, I think I'm going to not do anything here, since messing with a user-created zcash.conf has other problems.
