### ISSUE TITLE
Can't start/won't connect "Authentication Failed" on opening

### ISSUE THREAD

**Issue by Walley303** [ZcashFoundation/zecwallet#143]
"Starting embedded zcashd." Then:

![zecwallet_error](https://user-images.githubusercontent.com/51377765/58896756-a87d3280-86c4-11e9-94fb-c9dde2c1d386.jpg)

"Authentication failed. The username/password you specified was not accepted by zcashd. Try changing it in the Edit->Settings Menu."

The above message happens every time I open ZecWallet on my Mac (OSX 10.13.6). If I click through to the main window I can find no way to set up a password or username or anything. "No connection" is never resolved. In settings there is an option to input Host, Port, RPC username, RPC password, but I have no idea what RPC is. I am at a loss of what to do.

**Comment by adityapk00** [comment]
Hmm, that's strange. Can you try one thing for me please:

Can you delete your `zcash.conf` file, which is in `~/Library/Application Support/Zcash/zcash.conf` and then start ZecWallet again to see if that works?

Also, just to be sure - You downloaded it from the website, right? (And didn't compile it yourself?)

You can also try a new version that I just released to see if that works. https://github.com/ZcashFoundation/zecwallet/releases

**Comment by Walley303** [comment]
OK thanks! That seems to work now.

Quick follow-up, if I may: Every ZEC wallet I've tried seems to want me to run a node in order to use z-addr's. Is this an essential element to use the privacy features of ZEC?

**Comment by adityapk00** [comment]
Great. 

Yeah, ZEC currently needs the full blockchain to support the privacy-preserving z-addresses, but there are some new technologies that will make light clients possible, which should come pretty soon.
