### ISSUE TITLE
accidentally sent all my zec to ZecWallet donation

### ISSUE THREAD

**Issue by xiedidan** [ZcashFoundation/zecwallet#145]
I accidentally sent about 6 ZEC to ZecWallet donation address. zs1gv64eu0v2wx7raxqxlmj354y9ycznwaau9kduljzczxztvs4qcl00kn2sjxtejvrxnkucw5xx9u
Could you kindly return it to me?
Thanks.

**Comment by adityapk00** [comment]
@xiedidan , Can you send me another 0.001 ZEC Tx from the same address to verify your address. Also please include the same message in the memo field, so I can verify that it is really you.

**Comment by xiedidan** [comment]
@adityapk00 OK, since I sent all my ZEC already, I have to mine another 0.001 ZEC (currently I got no credit card to buy from market). It will take 1-2 days. I'll send as soon as the mining pool payout arrives. Thanks.

**Comment by xiedidan** [comment]
@adityapk00 Just sent 0.00100026 ZEC to zs1gv64eu0v2wx7raxqxlmj354y9ycznwaau9kduljzczxztvs4qcl00kn2sjxtejvrxnkucw5xx9u.
Thanks.

**Comment by adityapk00** [comment]
I have returned it.

**Comment by xiedidan** [comment]
Received. Thanks a lot. :-)
