### ISSUE TITLE
t-Addr List under "Receive" Tab Unpopulated

### ISSUE THREAD

**Issue by RealityRipple** [ZcashFoundation/zecwallet#146]
I can understand why you wouldn't list used t-Addrs in the Receive list, but unused ones in the Address Book should be included in the list, shouldn't they?

**Comment by adityapk00** [comment]
Thanks for reporting this. What version of ZecWallet are you using?

I just released v 0.7.1 which fixes some of these issues. Could you try that?

**Comment by adityapk00** [comment]
On second thought, this particular feature (show addressbook t-Addrs) is a good idea. I just implemented it. It'll be in a new release tomorrow.

**Comment by RealityRipple** [comment]
You may wish to add some kind of GUI-text notice to let users know they can "sticky" a receiving t-Addr by adding it to the Address Book, as well.

**Comment by adityapk00** [comment]
In 0.7.2
