### ISSUE TITLE
.zcash data - Windows and Linux - File Server Share

### ISSUE THREAD

**Issue by NeoBeum** [ZcashFoundation/zecwallet#149]
I've currently setup two virtual machines, one Windows 10, one Ubuntu 18.04, and am currently sharing the block and chainstate files in the .zcash directory.

I'm not running both machine synchronously, only one of the VMs uses the file server share at a time, but so far, it seems like zecwallet is happy to run on Windows and Ubuntu using the network share. Zecwallet is currently syncing the blocks.
Ubuntu is using CIFS NTLMSSP for SMB 3.0.
Windows is using SMB Direct.
I just wanted to share this information.

I will post back if there is something catastrophic with data corruption.

![zecwallet](https://user-images.githubusercontent.com/12646422/61002492-ca8f6200-a3a0-11e9-99cd-fcc3455f5cf9.jpg)

**Comment by adityapk00** [comment]
This is a rather unusual setup, but I'm glad its working. Let me know if you run into any weird issues.

**Comment by NeoBeum** [comment]
The Windows seems to sync faster than Ubuntu... the VM crashed last week during sync and there must have been some sort of overflow, (I think because I didn't allocate enough RAM) because the dynamic virtual disk that was storing the data blew up to 180GB
