### ISSUE TITLE
Eternal sync = Eternal generation of "t" addresses (BUG)

### ISSUE THREAD

**Issue by russianboss69** [ZcashFoundation/zecwallet#150]
Windows 10 Pro x64 / Windows 8.1 x64
ZecWallet v0.7.2

---

The wallet is never synchronized because during synchronization new "t" addresses are constantly being created.

After 24 hours, there are already more than 2000 of them.

During synchronization and receiving new blocks, the wallet scans all addresses in this block. For this reason, the program hangs at about 20% synchronization.

Zcashd does not have this error. If you want to have a complete synchronized node on your PC, first run zcashd.exe (C:\Program Files (x86)\zec-qt-wallet\zcashd.exe) and wait for complete synchronization and then run the GUI version of the wallet.

**Comment by russianboss69** [comment]
Perhaps this is the Main problem why ZecWallet is not used by many users.
I asked my two friends to install zecwallet on the PC. Both noticed that the wallet is constantly increasing.
I left the pc for 2 hours with the wallet turned on. A total of +315 addresses.

**Comment by adityapk00** [comment]
How are you checking for the 2000 addresses? Are you running `./zcash-cli listaddresses`? Is that returning 2000 addresses?

**Comment by adityapk00** [comment]
Fixed in 0.7.3

Thanks for reporting this!

**Comment by russianboss69** [comment]
Now everything is fine. Thanks! :-)
