### ISSUE TITLE
Permanent crash after closing the wallet (Windows 8.1 x64)

### ISSUE THREAD

**Issue by russianboss69** [ZcashFoundation/zecwallet#152]
Windows 8.1 x64

---

If the wallet was launched for more than 10-15 minutes and at this time new blocks were created after an attempt to close the wallet, a crash occurs. Problems on Windows 10 x64 not identified.

---------------------------

zec-qt-wallet: zecwallet.exe - Ошибка приложения
Инструкция по адресу "0x004c09b0" обратилась к памяти по адресу "0x00000000". Память не может быть "read".

---------------------------

Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	zecwallet.exe
  Версия приложения:	0.0.0.0
  Отметка времени приложения:	5d264105
  Имя модуля с ошибкой:	zecwallet.exe
  Версия модуля с ошибкой:	0.0.0.0
  Отметка времени модуля с ошибкой:	5d264105
  Код исключения:	c0000005
  Смещение исключения:	00000000000c09b0
  Версия ОС:	6.3.9600.2.0.0.256.4
  Код языка:	1049
  Дополнительные сведения 1:	54bd
  Дополнительные сведения 2:	54bd2188e3dd5e4c8f233171a6e1d050
  Дополнительные сведения 3:	796a
  Дополнительные сведения 4:	796a1d5408b5f819df8bafdc6b006f20

![zw072_err](https://user-images.githubusercontent.com/52780881/61051484-a780a480-a3d8-11e9-960e-222865bf20ba.jpg)

**Comment by adityapk00** [comment]
Fixed in 0.7.4
