### ISSUE TITLE
Permanent crash after import key with zcash-cli (BUG)

### ISSUE THREAD

**Issue by russianboss69** [ZcashFoundation/zecwallet#153]
Windows 8.1 x64 / Windows 10 Pro x64
ZecWallet v0.7.2

Sequencing:

1. Delete "wallet.dat" from "C:\Users\Home\AppData\Roaming\Zcash"
2. Run ZecWallet (wait until the program is fully loaded and create a new "wallet.dat")
3. Import new key with zcash-cli (zcash-cli.exe z_importkey "...z key..." yes 565000)
4. Make any transactions (important!)
5. Close ZecWallet (we get 1st crash)
6. Run ZecWallet again = **Permanent crash** (the wallet will never start again)

After removing "wallet.dat", the program will run again without any errors.

**Comment by adityapk00** [comment]
You've discovered a crash in the underlying zcashd. zcashd is crashing with:
```
zcashd: wallet/wallet.cpp:1045: void CopyPreviousWitnesses(NoteDataMap&, int, int64_t) [with NoteDataMap = std::map<SaplingOutPoint, SaplingNoteData>; int64_t = long int]: Assertion `nWitnessCacheSize >= nd->witnesses.size()' failed.
bash: “./zcashd” terminated by signal SIGABRT (Abort)
```
Can you file this issue with the zcashd team here: https://github.com/zcash/zcash/issues
