### ISSUE TITLE
Donation address is not removed from the address book! (BAD IDEA)

### ISSUE THREAD

**Issue by russianboss69** [ZcashFoundation/zecwallet#154]
Donation address is not removed from the address book! 

If I create a new entry in the address book, in this case the donate's address can be deleted BUT after restarting the program or deleting my address, the donate address appears again.

With this functionality may send the coins to the wrong address!

**Comment by russianboss69** [comment]
https://github.com/ZcashFoundation/zecwallet/issues/145
https://github.com/ZcashFoundation/zecwallet/issues/134
https://github.com/ZcashFoundation/zecwallet/issues/132

This functionality is definitely a **bad idea**! I myself noticed at the last moment that I was sending money to donation address.

**Comment by adityapk00** [comment]
Fixed in 0.7.3
