### ISSUE TITLE
"t" addresses are not displayed in the dropdown list (BUG)

### ISSUE THREAD

**Issue by russianboss69** [ZcashFoundation/zecwallet#155]
Windows 8.1 x64 / Windows 10 Pro x64
ZecWallet v0.7.2

Sequencing:

0. Run ZecWallet
1. Go to the tab "Receive"
2. Select the t-Addr field and click on the "New Address" button several times.
3. Go to any other tab
4. Go to the tab "Receive", select the t-Addr field

Now we can not see the old "t" address. The drop-down list is empty.

![zw072](https://user-images.githubusercontent.com/52780881/61050858-7fdd0c80-a3d7-11e9-9a27-565e2a5506e4.jpg)

**Comment by adityapk00** [comment]
This is actually intended behavior. Old t addresses that have 0 balance aren't displayed in the dropdown to discourage re-use of t addresses for privacy reasons (even though they are present in the wallet).

Only t-addresses that have a balance or an in the address book are displayed
