### ISSUE TITLE
Duplicate Label Names in the Address Book

### ISSUE THREAD

**Issue by RealityRipple** [ZcashFoundation/zecwallet#156]
Currently, if you add a new address to your Address Book with the same label as an existing address, the existing address is removed from your Address Book, and the new one takes its place. This seems like it could easily lead to user confusion. I suggest one of three possible better actions:

1. The system allows multiple addresses with the same label. This may lead to further confusion, though.
2. The Address Book prompts users with a Message Box that the new address will overwrite the old address in the Address Book.
3. The label of the old address gets unset or set to "Unlabeled#X".

I suggest option 3, personally, but it's not my decision to make.

**Comment by leto** [comment]
I agree that current behavior can potentially lose data if done accidentally, and changing it to one of the 3 options would be better.

I vote for 2 since that seems most user-friendly to me

**Comment by adityapk00** [comment]
I decided to prevent duplicate labels and let the user decide what to do.

**Comment by adityapk00** [comment]
Fixed in 0.7.4
