### ISSUE TITLE
Delete any entry from "Address Book" and click "Pick" = Crash (BUG)

### ISSUE THREAD

**Issue by russianboss69** [ZcashFoundation/zecwallet#157]
Windows 8.1 x64/10 Pro x64
ZecWallet v0.7.3

Sequencing:

1. Run ZecWallet, go to Address Book
2. Add any entry (1-2-3 records are possible)
3. Delete newly created entry (any)
4. Click on the "Pick" button = Crash

![073_pick](https://user-images.githubusercontent.com/52780881/61072272-7917bf00-a402-11e9-9a50-cd7df63ad0b2.jpg)

**Comment by adityapk00** [comment]
Fixed in 0.7.4
