### ISSUE TITLE
(Suggestion for improvement) Ask when you first start the wallet about the automatic updates (Good for PRIVACY)

### ISSUE THREAD

**Issue by russianboss69** [ZcashFoundation/zecwallet#161]
When you first start the program it would be great to ask about the automatic updates (Electrum experience):

---

Titile: ZecWallet - Automatic check for updates
Description: For security reasons, we recommend always using the latest version of ZecWallet. Notify you if a new version of ZecWallet is available?

Yes No

---

Also, this option should be displayed in the "Settings" section for future changes.

[x] Automatically check for software updates

---

Thus, the user himself chooses whether he wants the program to access the external server on its own or everything happens in manual mode.

**Comment by adityapk00** [comment]
Fixed in 0.7.4
