### ISSUE TITLE
Translations into different languages. Ready to help with Ukrainian and Russian :-)

### ISSUE THREAD

**Issue by russianboss69** [ZcashFoundation/zecwallet#164]
It would be great, by analogy with other programs, to add the ability to select a language.

For example, create a folder in which to place an XML file for each language. The program will understand what languages are available to it and use them. Example https://download.truecrypt.ch/language-packs/

Over time, the volunteers will translate the program into all languages :) I personally can help with the translation into Ukrainian and Russian :-)

**Comment by adityapk00** [comment]
We already have support for multiple languages. We'd love to have Russian & Ukrainian.

Instructions are here: https://docs.zecwallet.co/translations/

**Comment by russianboss69** [comment]
Excellent :)
