### ISSUE TITLE
"Report Bug" Button

### ISSUE THREAD

**Issue by russianboss69** [ZcashFoundation/zecwallet#165]
It would be great to add the "Report Bug" button to the Help section.
After clicking, a window with text opens.

Text example:
---
Please report any bugs as issues on github:
<a href="https://github.com/ZcashFoundation/zecwallet/issues">https://github.com/ZcashFoundation/zecwallet/issues</a>

Before reporting a bug, upgrade to the most recent version of ZecWallet (latest release or git HEAD), and include the version number in your report. Try to explain not only what the bug is, but how it occurs.

**Comment by adityapk00** [comment]
Fixed in 0.7.4
