### ISSUE TITLE
Validate an address

### ISSUE THREAD

**Issue by leto** [ZcashFoundation/zecwallet#171]
A way to run `validateaddress` via the GUI would be valuable to answer the questions:

* Is this address in this wallet?
* Is this address watchonly?
* Is this address a valid script?
* What is the pubkey of this address?

**Comment by adityapk00** [comment]
This is a good idea! I'll add it tomorrow.

**Comment by adityapk00** [comment]
In 0.7.6

**Comment by leto** [comment]
@adityapk00 Thanks! 🤘
