### ISSUE TITLE
Questions about zecwallet

### ISSUE THREAD

**Issue by Nokia808** [ZcashFoundation/zecwallet#175]
Hi. I have 2 questions:

1) does your wallet is a decentralized wallet like ("electrum" for bitcoin) ?

2) is there need to download blockchain for this wallet or it is like electrum being lightweight wallet ?

3) what is diffirence between this wallet & zepio wallet that also provided by you ? Which is better ?

4) there is Android package on Google play called zecWallet:
https://play.google.com/store/apps/details?id=com.adityapk.zcash.zqwandroid
But on your repository here you do not says that there is Android package & I did not see such .apk on your release page here !
It look like that it need Desktop wallet already installed like the way of Whatsapp on Desktop need user to open Whatsapp on mobile or some thing like this ...... !
Please can you conform that this Android package ?

**Comment by adityapk00** [comment]
1. Yes, ZecWallet is decentralized. It independently downloads the blockchain and verifies it
2. Right now yes, but there's a new project that will allow a light-wallet to be used. 
3. ZecWallet and Zepio are different wallets built by different teams, even though the have similar functionality
4. The Android app's APKs are available on the project's github page: https://github.com/adityapk00/zqwandroid/releases

**Comment by Nokia808** [comment]
@adityapk00 
Many thanks ! Only one thing: you said "zecwallet is a lightweight wallet like electrum right now. But there is new project will make lightweight wallet also possible." Can you kindly mention this new project & it's link, please.

**Comment by adityapk00** [comment]
https://grants.zfnd.org/proposals/1726546144-zecwallet-desktop-light-client
