### ISSUE TITLE
transactions not showing

### ISSUE THREAD

**Issue by SherazAawan** [ZcashFoundation/zecwallet#179]
i reinstalled windows and now the wallet is only showing 1 transaction. Another transaction is not showing
what should i do?

**Comment by mistfpga** [comment]
This may sound silly, but can you create a new t address and a new z address, give them both a label if possible then see if that fixes the issue.

**Comment by SherazAawan** [comment]
NO EFFECT
    On Monday, September 9, 2019, 09:08:13 PM GMT+5, mistfpga <notifications@github.com> wrote:  
 
 
This may sound silly, but can you create a new t address and a new z address, give them both a label if possible then see if that fixes the issue.

**Comment by adityapk00** [comment]
Can you provide more details? 

What transaction is not showing? Was it a t-address or a z-address? Is your balance correct? Are you seeing all your addresses properly?

**Comment by SherazAawan** [comment]
Z AddressBalance not correctAddresses missing
    On Tuesday, September 10, 2019, 09:25:31 PM GMT+5, adityapk00 <notifications@github.com> wrote:  
 
 
Can you provide more details?

What transaction is not showing? Was it a t-address or a z-address? Is your balance correct? Are you seeing all your addresses properly?

**Comment by adityapk00** [comment]
If your z address is missing, you will need to import the private key for that or restore it from a backup

**Comment by SherazAawan** [comment]
the private key i had i imported and it only brought back 1 transaction the T address one is still missing
    On Wednesday, September 11, 2019, 06:55:32 AM GMT+5, adityapk00 <notifications@github.com> wrote:  
 
 
If your z address is missing, you will need to import the private key for that or restore it from a backup

**Comment by adityapk00** [comment]
Note that private keys for z-addresses and t-addresses are different. If you're missing a t-address, you also need to import the corresponding t-address's private key.
