### ISSUE TITLE
Impossible to import private Keys (ZecWallet v.0.7.8.)

### ISSUE THREAD

**Issue by Maxim3474** [ZcashFoundation/zecwallet#181]
Hi dear Developer, i have the lastest version of ZecWallet v.0.7.8. I tried to import my private key for one T-Address, but there hasnt been imported anything. The Address hasnt even appeared in the "Addresses Balances". 

ZecWallet shows me that rescan is seccessfully completed, but there is nothing more.

ZecWallet shows me too, it accepted my private key but it showing nothing in the "Addresses Balances".  Pravite key is 100% correct because Zecwallet accepted it. 

The whole blockchain is downloaded beforehand (ZecWallet is 100% syncronized).

I dont know, what to do, because private key for one T-address accepted but there hasnt been my addresss. Help me please =)) and thanks a lot

**Comment by adityapk00** [comment]
I assume you've tried to rescan to check for any missed transactions?
https://docs.zecwallet.co/troubleshooting/#how-to-perform-a-wallet-rescan

If the rescan has not fixed the problem, you may not have the right private key. Are you sure you have the correct private key? You can check by importing the key via `zcash-cli` and see if you get the correct address back. You should double-check with a block explorer to make sure that the address you have actually does have balance.

**Comment by Maxim3474** [comment]
H
![1](https://user-images.githubusercontent.com/40694667/64994818-4eeeeb80-d8e2-11e9-9188-e9ec9e05cbc9.png)
![2](https://user-images.githubusercontent.com/40694667/64994820-51514580-d8e2-11e9-8099-ccd2a25718d2.png)

**Comment by Maxim3474** [comment]
Hi dear Support, my Problem is solved =) my t-address has been recovered. I just had to wait, it took less then 15 Minutes to rescan my external HDD. The main Problem was it wast showed the progress bar. 

I have some Questions:
1) Why cant i encrypt my ZEC (there is no encryption there)? Do i have to encrypt my Disk Space, where i store my wallet.dat? What sort of encrypting Programm do you recommend (BitLocker, Vera Crypt) or others? 

Thanks a lot :)

**Comment by adityapk00** [comment]
1. Wallet encryption is not yet supported, but should come soon to the new ZecWallet lightclient
