### ISSUE TITLE
Please support 32 bits Windows !

### ISSUE THREAD

**Issue by ytrezq** [ZcashFoundation/zecwallet#184]
And configure the 64 bits `.msi` to refuse installing on a 32 bits system.

**Comment by ytrezq** [comment]
Because yes ! There are still peoples without a computer having a 64 bits ᴄᴘᴜ and who need to access their sapling Zcash before they get their 64 bits computer repaired 6 week later.

**Comment by adityapk00** [comment]
Sorry, there are too many dependencies that don't work on 32-bit builds. This will not be supported.
