### ISSUE TITLE
zcashd is not yet ready...wait for the UI to load

### ISSUE THREAD

**Issue by acgithu** [ZcashFoundation/zecwallet#191]
when zcashd is ready .?? It is th third day that the software is running : How is it possible that people download the wallet , install it , start it and must know  where is cashd , how start cashd , find the right version, the last version . In the bottom the  message 👍 No connection which conecction ??? with which site ?? which sofware ?? . The pc is connected because i use many  banks for trading and i see the data in real time. My pc is in i7, with 12GB of ram an ssd disk...and a TB fixed disk. Always the same message . Every one to find his coins must study,   for how many days wait ????
thanks

**Comment by adityapk00** [comment]
If you don't want to download the full blockchain, please try the lightclient that was just released: https://forum.zcashcommunity.com/t/zecwallet-cli-v1-0-is-here/35182. It's Command Line only for now, but the UI version should be available in a couple of weeks!
