### ISSUE TITLE
wallet.dat corrupted

### ISSUE THREAD

**Issue by kolkara** [ZcashFoundation/zecwallet#193]
after updating to the latest version, the program produces this.. what should i do?
![12](https://user-images.githubusercontent.com/56769732/67149237-46fbe000-f2c2-11e9-867e-4538624b4ec8.jpg)

windows / 64 / chrome

**Comment by adityapk00** [comment]
If `zcashd` is complaining that your wallet is corrupted, you'll have to restore it from a backup. 

You can also try to perform a rescan or a reindex (or both) to see if `zcashd` can recover it. 

https://docs.zecwallet.co/troubleshooting/#how-to-perform-a-wallet-rescan
