### ISSUE TITLE
ZECWallet compatibility

### ISSUE THREAD

**Issue by lorissmailbox** [ZcashFoundation/zecwallet#196]
Is ZECWallet compatible with the Tails OS or an Ubuntu Live OS on USB Stick ?

Thank you,

**Comment by adityapk00** [comment]
Yes, Zecwallet will run on any debian-based OS. 

Be warned that this will download the full blockchain (~25 GB), which needs to fit on the USB stick. 

You should really use the lightclient (https://github.com/adityapk00/zecwallet-lite) If you're running from a USB stick
