### ISSUE TITLE
Transaction failed to send

### ISSUE THREAD

**Issue by kwmtnkabc** [ZcashFoundation/zecwallet#198]
Sending a transaction using a private address failed, confirmations: -1
![image_2019_11_06T15_05_39_378Z](https://user-images.githubusercontent.com/43038218/68309838-01287f80-00ea-11ea-802e-68b4769f79f1.png)

**Comment by zancas** [comment]
Hi @kwmtnkabc !   Did you attempt to send a negative value?

**Comment by kwmtnkabc** [comment]
Did not attempt to send a negative value, send two transactions in a row, the first success, the second confirmation: -1 Then I continue to send all confirmation: -1

**Comment by adityapk00** [comment]
Can you provide more details? Did you have enough balance? Did you have confirmed funds? Can you paste your zcashd log here?

**Comment by zancas** [comment]
Or some redacted subset?

**Comment by leto** [comment]
This is a bug in zcashd itself

**Comment by adityapk00** [comment]
This was possibly a bug with zcashd, which has been fixed in 2.1.0, which is now released.

**Comment by kwmtnkabc** [comment]
Thank you
