### ISSUE TITLE
Synching Error

### ISSUE THREAD

**Issue by 1AT1** [ZcashFoundation/zecwallet#201]
zcashd has no peer connections (v 2000753)
This error is preventing me from downloading all the block chain I need to start mining.
I encountered this error on v0.7.9
![2019-11-11](https://user-images.githubusercontent.com/57643656/68624209-39570600-04ce-11ea-86a3-55e9df41b4f3.png)

**Comment by rex4539** [comment]
Can you please post your `debug.log` and the contents of `zcash.conf`?

Please omit the `rpcpassword` as this is secret.

**Comment by adityapk00** [comment]
Also, please see our help section: https://docs.zecwallet.co/troubleshooting/#my-node-isnt-syncing-or-is-slow-to-sync
