### ISSUE TITLE
[Mac OS X] Menu bar unresponsive on startup 

### ISSUE THREAD

**Issue by pacu** [ZcashFoundation/zecwallet#209]
Please make sure you have the latest ZecWallet. : 0.8.1 👍 

**Describe the bug**
When opening ZecWallet, the app syncs to the latest block. then for a minute or so, even though the rest of the application is responsive, the file File, Edit, Apps and Apple icon of the menu bar don't work. 

**To Reproduce**
1. Open zecwallet
2. Click on any of the menu bars
3. See that they do not respond

**Expected behavior**
menu should work

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.15.1

**Additional context**
I'm running testnet

**Comment by rex4539** [comment]
I have reported this bug to @adityapk00 as well prior to the release and it seems to be related to Qt.

If you click anywhere outside of the app and then come back to the app, then the menus are accessible again.

**Comment by adityapk00** [comment]
Yes, I've tried to look into it, and it seems like a problem with Qt. I'll try spending some time again this week on it to see if I can fix it.

**Comment by pacu** [comment]
Cool, let me know if I can help testing it.

**Comment by adityapk00** [comment]
Fixed, since we switched to electron :)
