### ISSUE TITLE
libsodium source code SHA256 is not verified in build system

### ISSUE THREAD

**Issue by leto** [ZcashFoundation/zecwallet#210]
res/libsodium/buildlibsodium.sh could verify the SHA256 of the libsodium 1.0.16 dependency but currently does not

**Comment by leto** [comment]
An example of how to do this can be found here: https://github.com/MyHush/SilentDragon/blob/master/res/libsodium/buildlibsodium.sh

**Comment by adityapk00** [comment]
Zecwallet no longer uses libsodium download
