### ISSUE TITLE
Shielded balance incorrect

### ISSUE THREAD

**Issue by Quaternioneer** [ZcashFoundation/zecwallet#211]
My shielded balance is incorrect.

1. Received X at a t-address.
2. Sent X minus fee to myself from a t-address to a z-address.
3. Sent to a hardware wallet from the z-address.

The shielded balance should be 0 ZEC in the summary, but I still see X minus fees. 

Ubuntu 18.04 LTS
Zecwallet 0.8.1. The full node was started with zecwallet 0.8.0's zcashd.

**Comment by adityapk00** [comment]
Closing as stale
