### ISSUE TITLE
Zcashd not stopped when ZecWallet is closed

### ISSUE THREAD

**Issue by pacu** [ZcashFoundation/zecwallet#213]
Please make sure you have the latest ZecWallet. 

**Describe the bug**
Zcashd is not closed after the user quits Zec Wallet

**To Reproduce**
1. open ZecWallet
2. force quit ZecWallet

**Expected behavior**
everything related to ZecWallet is closed and deallocated from the system 

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.12

**Additional context**
I have a testnet Zcash.conf file 
I can't access the version of ZecWallet becase the menu does not work.

**Comment by adityapk00** [comment]
Should be fixed with the new Zecwalllet
