### ISSUE TITLE
New Electron Wallet Connects and Loads Remote Resources from Google Servers when it is Opened

### ISSUE THREAD

**Issue by s-rah** [ZcashFoundation/zecwallet#221]
Thanks to https://github.com/ZcashFoundation/zecwallet/blob/master/app/app.html#L6 this wallet for a privacy preserving cryptocurrency now loads remote resources from one of the largest surveillance corporations on the planet.

Confirmed in Wireshark:
![Screenshot_20200221_150314](https://user-images.githubusercontent.com/106626/75078742-56cb4100-54bb-11ea-833a-692c847f2194.png)

This was probably not intended behaviour.

**Comment by shanejonas** [comment]
Why close this, seems like a privacy leak?

If you are relying on google fonts, i recommend checking out this page to try and match something that is default on users systems:

https://meowni.ca/font-style-matcher/

**Comment by adityapk00** [comment]
It was closed because it was fixed (to load the font locally) in the referenced commit.
