### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zecwallet#225]
Steps:
Launch wallet.

What happened:
```
Failed to decode downloaded font: http://localhost:1212/dist/c04be2726a649bc04f4a71fb2d84edba.ttf
```

Expected result:
No error is logged.

**Comment by adityapk00** [comment]
Where are you seeing this error? In the Devtools console or on the command line? I can't seem to replicate this one. You're using a Mac, right?

**Comment by adityapk00** [comment]
Where are you seeing this error? In the Devtools console or on the command line? I can't seem to replicate this one. You're using a Mac, right?

**Comment by rex4539** [comment]
Devtools console on macOS.
