### ISSUE TITLE
Question on Wormhole Replay Attack (reuse of duplicate nonce)

### ISSUE THREAD

**Issue by s-rah** [ZcashFoundation/zecwallet#243]
I notice that the latest version has an unadvertised fix for the nonce replay issue I mentioned on twitter (https://twitter.com/SarahJamieLewis/status/1234585483482550273)

However, it would appear the actual check is not correct: https://github.com/ZcashFoundation/zecwallet/blob/9d5c5f6c5507a9cbb64afae6561c222d1d68265b/app/companion.js#L343

This asserts a decryption error if the previous nonce is greater than the nonce in the package. However if the nonce is the same (i.e. compare == 0, which is strictly not " > 0") then the wormhole cans till send multiple copies of the same command (thus causing multiple spends) i.e. this patch seems to have no impact on duplicate nonces.

I can't find anywhere that would protect against duplicate nonces, unless I'm missing something?

**Comment by adityapk00** [comment]
I think you might be right. It should probably be `>= 0`.

Let me verify
