### ISSUE TITLE
Trace/breakpoint trap on Debian 9

### ISSUE THREAD

**Issue by alessandroponzo** [ZcashFoundation/zecwallet#245]
I got this error when I run zecwallet after install it with dpkg
Debian 9 kernel 4.9.0

**Comment by adityapk00** [comment]
Yeah, I can see this error too. Investigating...

**Comment by adityapk00** [comment]
This seems like a complex permissions problem with debian 9 that doesn't have a fix with debian 9. 

Workaround is to run 
```
sudo sysctl kernel.unprivileged_userns_clone=1
```

and then start `./zecwallet`

**Comment by adityapk00** [comment]
You could also try running the appimage with `--no-sandbox`
