### ISSUE TITLE
Zecwallet problem

### ISSUE THREAD

**Issue by lubhub612** [ZcashFoundation/zecwallet#249]
@adityapk00 I  have a problem regarding older version of ZECWallet,Help your suggestion to solve the problem,
problem give me  

/usr/bin/ld: out of memory allocating 264088949096448 bytes after a total of 1654784 bytes
collect2: error: ld returned 1 exit status

this type of error , but my swap memory is near 1 gb. 64 bit system , 50 gb space , currently 25 gb avaliable... 
![image](https://user-images.githubusercontent.com/45089340/76405030-89c36f00-63ad-11ea-8468-938110fea09a.png)

**Comment by adityapk00** [comment]
I think you've just run out of ram. Note that to compile Zecwallet, it needs a lot of RAM and a lot of free disk space, because of Qt. You need at least 8G of free RAM.

**Comment by lubhub612** [comment]
![image](https://user-images.githubusercontent.com/45089340/76491096-e462d680-6452-11ea-9530-dc1124937671.png)
@adityapk00  any link qt any releated to this please

**Comment by lubhub612** [comment]
Dev Team please help me? and I am cannot run new version of the zecwallet from digital ocean droplet. Please help me..

**Comment by adityapk00** [comment]
Google is your friend. Please download from here: http://download.qt.io/official_releases/qt/5.12/5.12.1/single/qt-everywhere-src-5.12.1.tar.xz

**Comment by lubhub612** [comment]
thnx for the download link, new zec wallet give me that type of error..
![image](https://user-images.githubusercontent.com/45089340/76645623-618b6a00-657f-11ea-9812-a4e73f8ffe32.png)

**Comment by lubhub612** [comment]
dear @adityapk00 a question to you, would you tell me how i can run new zecwallet from github code, 
just a curious to know, how I run zecwallet from code and how i run it on digital ocean droplet , how to view result on code comiplation.

**Comment by lubhub612** [comment]
Please help me for new zec wallet compilation,
