### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by humanizator** [ZcashFoundation/zecwallet#251]
Help!!! I sent myself to another (my) address, but the coins were stuck on the addresses for delivery (from which there are no private keys).
How to return coins?

**Comment by adityapk00** [comment]
You can extract all your private keys by doing `File -> Export All Keys`. If you really sent it to your own address, your private key will be there. 

If you sent it to another address that you don't control, then sorry, there is no way to recover your funds

**Comment by humanizator** [comment]
Thanks! Indeed, I sent coins to my addresses, but they left in the form of change to my other addresses (I did not save the private keys from these addresses). Coins during the day in the wallet were displayed at the addresses to which I sent them, but then an error occurred and with the current file "wallet.dat" the wallet "zecwallet full node 9.5" did not start. I took a copy of the archived "wallet.dat" of 2018 (the very first copy), but on it, after full synchronization with the network, only 2 private keys. The old file was deleted, but then restored, it is partially damaged. Need a program to extract text data from a file "wallet.dat" 60 coins lost

**Comment by adityapk00** [comment]
Are the change addresses t addresses or z addresses?

Do you still have the new (the corrupted) wallet.dat?

**Comment by humanizator** [comment]
I did this: I copied these addresses (I have private keys from them) and sent coins to them
t1JGvyashr4KnM66SWhLUvQHx1NMug3EkCt
t1J8Vrv8Jh2ErWbBpRnvLAy8Y3XdvwYAovn
t1HySv2oQDhTQoRK614u9cVze2aDmuCGkth
t1J1yY5u216jBJ2zfdM7FzF33rLXrKo2FMm
but remained in the form of change on these
t1gfPKWGFrLfmsf6JQefjuCncHskhEhNgPi
t1LyawFwHmXR7tJvcU4G9jX9ZyYMtiLTDUB
t1QJ9evRNuxzYeTaGRvpkv2obkpRacmjBit

**Comment by humanizator** [comment]
> "Do you still have the new (the corrupted) wallet.dat?"
I have a damaged file "wallet.dat"

**Comment by adityapk00** [comment]
I'm sorry to tell you that unless you have either (1) The corrupted `wallet.dat` OR (2) the private keys to the change addresses, your coins are not recoverable. 

Do you have either?

**Comment by adityapk00** [comment]
This is a zcash issue, and I would post on the zcash forums to see if anyone can help you recover a corrupted `wallet.dat`

https://forum.zcashcommunity.com

**Comment by humanizator** [comment]
file restored but not recognized by client

**Comment by humanizator** [comment]
in this file should be priv keys to the addresses I need. you need to extract text data from it

**Comment by humanizator** [comment]
is it possible to extract data from a file wallet.dat?

**Comment by humanizator** [comment]
maybe i will send you a file? if you restore, I will share coins with you

**Comment by humanizator** [comment]
Good afternoon again! I want to tell you that you, as a developer of crooked software, are to blame for the loss of my coins, and now I will prove it to you! With the loss of 60 coins, I have already come to terms. So now I tried again to transfer the coins to my wallet to my other address, it turned out the following: the transferred coins to address A appeared to be unused at address B. I dump the private keys, I have a key from address A, but not from address B. But while the wallet is working, I can transfer coins from address B (although I don’t have a private key). As soon as the program issued an error and can no longer start with this wallet - that's all, I lost money, I told them goodbye! This situation led to the loss of my money last time!

**Comment by humanizator** [comment]
This is a story about how a sufficiently competent person wanted to start using cryptocurrency and lost money due to an error in the software. And I lowered paid my personal money!

**Comment by adityapk00** [comment]
There's now a special build of Zecwallet with a master branch `zcashd` here: https://www.zecwallet.co/masterzcashd.html

You can try to use it and see if it helps.
