### ISSUE TITLE
storing shielded history in zecwallet fullnode

### ISSUE THREAD

**Issue by jbp6jd7k** [ZcashFoundation/zecwallet#255]
currently only able to see history of t addresses and z address receives. not able to see shielded and unshielding transactions

**Comment by adityapk00** [comment]
Unfortunately, this is a known issue. `zcashd` doesn't store outgoing  z transactions, so we end up with inconsistencies in the tx history. 

You should use Zecwallet Lite if you want to keep full track of all transactions in the wallet.

**Comment by jbp6jd7k** [comment]
how does zecwallet lite retrieve the zaddress history if it depends on a remote zcashd node if zcashd doesnt store the history?

**Comment by adityapk00** [comment]
zcashd only stores partial history. You can see recieved (non-change) transctions, but not sent transactions from z addresses. Zecwallet attempts to reconstruct the tx history with this partial info, but of course, it doesn't work in all cases. 

Of course, balances are always correct for all addresses.

**Comment by adityapk00** [comment]
Zecwallet Lite uses a different protocol than the `zcashd`. This protocol has full support for incoming and outgoing (t and z) transactions along with memos.

**Comment by adityapk00** [comment]
Note that Zecwallet Lite depends on the remote node only for block data. It does all it's own scanning and tx tracking, so it doesn't depend on the remote node for any history or balances.

**Comment by jbp6jd7k** [comment]
thank you for your clarification. it seems if i want to store zaddress history and validate all my transaction history, i should run zcashd locally + zecwallet lite and point it to my own node?

**Comment by adityapk00** [comment]
That is correct. Note that you need a "lightwalletd" in front of the zcashd for the Zecwallet Lite client to talk to. 

http://github.com/adityapk00/lightwalletd

**Comment by jbp6jd7k** [comment]
thank you! much appreciated!
