### ISSUE TITLE
Allow mobile connected app to send ZEC instead of $ amount

### ISSUE THREAD

**Issue by 01BTC10** [ZcashFoundation/zecwallet#256]
Since about 2-3 weeks the android app doesn't find the live ZEC price so the value is set to 0. Since the sent amount has to be typed in $ instead of ZEC unit it is now impossible to send any amount. It also make it difficult to send all ZEC unit from an address since I need to find the correct $ amount by trial and error.

**Comment by adityapk00** [comment]
There was an issue with the price API several weeks ago, which was fixed in Zecwallet 0.9.7. Do you have the latest zecwallet release?

In any case, I'll also add the ability to send in ZEC in the mobile app.

**Comment by 01BTC10** [comment]
> There was an issue with the price API several weeks ago, which was fixed in Zecwallet 0.9.7. Do you have the latest zecwallet release?
> 
> In any case, I'll also add the ability to send in ZEC in the mobile app.

I'm using the current google play version:

ZecWallet android version: 0.3.2
ZecWallet server version: 0.8.1

It seems that the Arch linux AUR package hasn't been updated yet.

**Comment by adityapk00** [comment]
I don't maintain the Arch Linux AUR, so that must an unofficial version. Please download the latest version from github directly: https://github.com/ZcashFoundation/zecwallet/releases
