### ISSUE TITLE
  Syncing 0.0% all the time.

### ISSUE THREAD

**Issue by Malfoy12** [ZcashFoundation/zecwallet#257]
zcashd.exe have zero connections.
also i have 8232, 8233, 18232, 18233 ports closed.
how i can resolve this problem?

**Comment by adityapk00** [comment]
You might need to open the 8233 port, which is the p2p port through which zcashd syncs. Please look at our troubleshooting guide: https://docs.zecwallet.co/troubleshooting/#my-node-isnt-syncing-or-is-slow-to-sync

Also, running a full node needs some technical involvement, so if you're having trouble or aren't technical, I'd recommend using the Lite wallet - www.zecwallet.co
