### ISSUE TITLE
Error Initializing Lightclient Error: failed to fill whole buffer

### ISSUE THREAD

**Issue by protongirl** [ZcashFoundation/zecwallet#260]
I have money in this Wallet but cant acces :( only way that I found is %Appdata% C:\blabla\AppData\Roaming\Zcash and delete zecwallet-light-wallet then I can create new wallet, but I dident save the seed :/ can anyone help me please???

[![Screenshot_1](https://user-images.githubusercontent.com/65078024/81476180-b90d2580-9210-11ea-8c24-aaa8478ca148.png)
](url)

I have  Zecwallet Lite v1.1.9

**Comment by adityapk00** [comment]
Filed in the lite client github repo.
