### ISSUE TITLE
Failed to stat zcashd. Giving up! please file and issue with Zec wlalet

### ISSUE THREAD

**Issue by GodsSpecialGift** [ZcashFoundation/zecwallet#261]
how to load the crashed wallet

**Comment by adityapk00** [comment]
This looks like an issue with zcashd. What does the debug.log file say?

**Comment by sebastiendan** [comment]
I've just faced the same error message on a first zecwallet restart after a whole completed sync, on testnet.
Here's my [debug.log](https://github.com/ZcashFoundation/zecwallet/files/4619437/debug.log).

**Comment by adityapk00** [comment]
@sebastiendan Your debug.log doesn't seem to have many clues. You need to run `zcashd` directly from the command line and see what errors you are getting. 

Please note that using the Full Node version requires that you download the full blockchain (~28GB) and have some expertise with the command line. You want a easier-to-use wallet, please use Zecwallet Lite, which doesn't need to download the blockchain. www.zecwallet.co

**Comment by sebastiendan** [comment]
Thanks @adityapk00 for your reply.

A couple of things:
- I first tried to use the Zecwallet Lite CLI, but I couldn't use it with the testnet `lightwalletd` endpoint:

```
$ zecwallet-cli --server https://lightd-test.zecwallet.co:443
Error during startup: failed to lookup address information: nodename nor servname provided, or not known
```

- I tried also the Zecwallet Lite macos client but couldn't find how to aim at testnet

- I tried to build `zcashd` as well but honestly the documentation makes it quite unclear whether it's possible to build it on other platform than Debian (my understanding is that it should be possible but is not officially supported?)

```
$ ./zcutil/build.sh -j$(nproc)
zsh: command not found: nproc
readlink: illegal option -- f
usage: readlink [-n] [file ...]
./zcutil/build.sh: line 30: ./depends/config.guess: No such file or directory
```
Sharing the build script error above, I realize one needs to `cd zcutil` and then `build.sh`

**Comment by adityapk00** [comment]
Ah, you're using testnet. Sorry, the `https://lightd-test.zecwallet.co:443` server doesn't exist anymore, because no one was using it. You need to compile and run your own zcashd if you want to run testnet. 

It looks like you're missing a bunch of tools on your macos installation. You need to install homebrew, then install "nproc". Please see the help at: https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html (under the MacOS section)

**Comment by sebastiendan** [comment]
Indeed I was missing these tools, I can start `zcashd` now 👍
