### ISSUE TITLE
Deprecated doc (zcash-cli)?

### ISSUE THREAD

**Issue by sebastiendan** [ZcashFoundation/zecwallet#262]
[This paragraph](https://docs.zecwallet.co/faq/#how-do-i-use-the-zcash-cli-command) in the documentation refers to the `zcash-cli` client and gives its location on mac.

I cannot find the client under `/Applications/zecwallet.app/Contents/MacOS/`, I cannot find the client anywhere.

**Comment by adityapk00** [comment]
@sebastiendan Since you are using the Full node, you need to run compile zcashd yourself, so that you can get the `zcash-cli`. Please see the zcashd docs for instructions. 

https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html
