### ISSUE TITLE
Error loading sapling-output.params. the error was: the response status was 403

### ISSUE THREAD

**Issue by Sheldon11F** [ZcashFoundation/zecwallet#263]
When starting installation on windows 7, an error occurs:

Error loading sapling-output.params. the error was: the response status was 403

What does it mean?

**Comment by Sheldon11F** [comment]
Failed to start zcashd. Giving up! Please look at the debug.log file.
C:\Users\User\AppData\Roaming\Zcash/debug.log
Please file an issue with Zecwallet


Zcash version v2.1.2-806923c (2020-04-23 12:46:54 -0700)
InitParameterInteraction: parameter interaction: -proxy set -> setting -listen=0
InitParameterInteraction: parameter interaction: -proxy set -> setting -discover=0
InitParameterInteraction: parameter interaction: -listen=0 -> setting -listenonion=0
Using OpenSSL version OpenSSL 1.1.1a  20 Nov 2018
Using BerkeleyDB version Berkeley DB 6.2.23: (March 28, 2016)
Default data directory C:\Users\User\AppData\Roaming\Zcash
 Using data directory C:\Users\User\AppData\Roaming\Zcash
Using config file C:\Users\User\AppData\Roaming\Zcash\zcash.conf
Using at most 125 connections (2048 file descriptors available)
 Using 2 threads for script verification
scheduler thread start
Loading Sapling (Spend) parameters from C:\Users\User\AppData\Roaming\ZcashParams\sapling-spend.params
Loading Sapling (Output) parameters from C:\Users\User\AppData\Roaming\ZcashParams\sapling-output.params
Loading Sapling (Sprout Groth16) parameters from C:\Users\User\AppData\Roaming\ZcashParams\sprout-groth16.params

**Comment by adityapk00** [comment]
It is possible the params files are corrupted. Please delete everything in `C:\Users\User\AppData\Roaming\ZcashParams\` and try restarting. 

Note that Zecwallet Fullnode will download a lot of data and sync the full node. If you want a easier client that doesn't download the chain and syncs quickly, please checkout the Lite wallet www.zecwallet.co

**Comment by geb789** [comment]
@adityapk00 Zecwallet light not work not, could not get transparent date
