### ISSUE TITLE
When you start the program, the following message appears: "Could not connect to zcashd" I run the Program for the first time. Before that, I worked with 4 win. Please help me.

### ISSUE THREAD

**Issue by bessic** [ZcashFoundation/zecwallet#264]
When you start the program, the following message appears: "Could not connect to zcashd" I run the Program for the first time. Before that, I worked with 4 win. Please help me.

**Comment by adityapk00** [comment]
What platform are you running on now? You need to check the debug.log file. Please see https://docs.zecwallet.co/troubleshooting/#the-zcashd-debug-log

Also note that running the full node needs some expertiese. If you want a easy wallet that doesn't need sync, please check out the lite wallet. www.zecwallet.co
