### ISSUE TITLE
Synchronisation is very slow

### ISSUE THREAD

**Issue by dr34mup** [ZcashFoundation/zecwallet#265]
I installed and opened the wallet yesterday. Since then it crashed my pc one time and syncs really slow. I mean the synchronisation of the blockchain is at 2%....

zcashd.exe is <5% CPU usage.
Zecwallet Fullnode <1% CPU usage

Any idea how I can speed it up?

(Internet speed: 70Mb down/7Mb up)

**Comment by dr34mup** [comment]
Ok, I just started the zcashd.exe in the CMD and it is now at 8%. Something is wrong with the ZECwallet.

**Comment by adityapk00** [comment]
If you want really fast sync, please consider using the Zecwallet Lite wallet, which doesn't require a blockchain download. www.zecwallet.co

For Fullnode synchronization debugging, please see: https://docs.zecwallet.co/troubleshooting/#my-node-isnt-syncing-or-is-slow-to-sync
