### ISSUE TITLE
zcash and whonix

### ISSUE THREAD

**Issue by Sheldon11F** [ZcashFoundation/zecwallet#266]
Hi, can I install wallet on whonix os ? It's not working. I downloaded and installed Zecwallet_Fullnode_0.9.12_amd64.deb
It appears in the start menu but does not start! Nothing's happening! I've tried to run zecwallet.Fullnode-0.9.12.AppImage but nothing else is happening!

**Comment by Sheldon11F** [comment]
sudo dpkg -i Zecwallet_Fullnode_0.9.12_amd64.deb
Select a previously unopted zecwallet package.
(Reading the database ... 135,329 files and directories have been installed so far.)
Preparing for unpacking Zecwallet_Fullnode_0.9.12_amd64.deb ...
Unpacked zecwallet (0.9.12) ...
dpkg: package dependencies do not allow you to set up a zecwallet package:
 zecwallet depends on gconf2, however:
  There is no gconf2 package installed.
 zecwallet depends on gconf-service, however:
  No gconf-service package has been installed.
 zecwallet depends on libappindicator1, however:
  The libappindicator1 package has not been installed.

dpkg: bug in the processing of the zecwallet package (--install):
 dependency problems - leave untuned
Processed triggers for desktop-file-utils (0.23-4) ...
The triggers for mime-support (3.62) are processed ...
The triggers for hicolor-icon-theme (0.17-2) are processed...
There were errors in the processing of the following packages:
 zecwallet

**Comment by adityapk00** [comment]
You need to run `sudo apt install -f` to install the dependencies as well. 

I'll update the docs on this.

**Comment by paulbrigner** [comment]
I am having the same problem as Sheldon11F.  I'm installing on a fresh Debian GNU/Linux 11 (bullseye) system, and I had no problems setting up Zcashd and Zcash-cli.  I ran `sudo apt install -f` as suggested, but that appeared to remove zecwallet.  Any ideas what I am doing wrong?  Thanks!
