### ISSUE TITLE
Download fail to initiate

### ISSUE THREAD

**Issue by Az0321** [ZcashFoundation/zecwallet#268]
[debug.log](https://github.com/ZcashFoundation/zecwallet/files/4877910/debug.log)

Hello!

I run into an issue with my zecwallet setup, after downloading the 700MB file, I cannot download the whole block of 28GB for whatever reason and get this error message.
![Annotation 2020-07-06 102559](https://user-images.githubusercontent.com/67897963/86578059-1ef8fd80-bf73-11ea-8d9c-79798ba49bcf.png)

I checked and my antivirus does not interfere with the download, I have enough space on my SSD and.. I have a good internet connection.. I do not know what else to check (I also turn my PC off and on again ahah).
I attached the debug file if it helps.

Thanks for any support

**Comment by adityapk00** [comment]
I think the most likely explanation is that your params files are corrupted somehow. Please try deleting this directory: `\Users\User\AppData\Roaming\ZcashParams\`

I would recommend you also look at the Lite client - www.zecwallet.co. It is much much faster, doesn't need to download the blockchain and will allow you to backup your seed.
