### ISSUE TITLE
Better UX

### ISSUE THREAD

**Issue by the-tinderbox** [ZcashFoundation/zecwallet#270]
Hello guys. Thx for wallet, but i think you should do some usefull stuff like settings section, ability to start rescan via GUI, ability to send RPC commands via GUI, like bitcoin core. It's very hard to to these things via terminal on macOS. It's realy needed stuff. I think it's not difficult. Thx!

**Comment by adityapk00** [comment]
Sorry, a lot of these are not supported via RPC, so Zecwallet can't really implement them. 

These are all, of course, available via the Lite wallet UI.
