### ISSUE TITLE
zecwallet 

### ISSUE THREAD

**Issue by dinkaz132** [ZcashFoundation/zecwallet#276]
Привет после последнего обновления кошелька zecwallet fullnode  синхронизация не происходит

**Comment by pavanvoOfficial** [comment]
Hello, after latest update I can't sync my wallet

**Comment by tt2105** [comment]
Hello, after latest update I can't sync my wallet. ver.0.9.12/13
![not upd](https://user-images.githubusercontent.com/61073276/87912275-e5ee7c00-ca8e-11ea-862b-715ef2ca2099.jpg)
13

**Comment by adityapk00** [comment]
You are running into this issue: https://github.com/zcash/zcash/issues/4620 (Please follow along there)
