### ISSUE TITLE
Wallet wont sync up and I am on the new Zec wallet plz help stuck at 93.3 percent. 

### ISSUE THREAD

**Issue by GodsSpecialGift** [ZcashFoundation/zecwallet#277]
Hey guys wallet is freezing up as it is synchronizing up at 93.3% any ideas on what to do I am already on most up to date wallet. I am on the ZecFullnode. 0.9.13

**Comment by adityapk00** [comment]
You're running into this problem: https://github.com/zcash/zcash/issues/4620 Please follow along on that issue

**Comment by GodsSpecialGift** [comment]
Does this mean they are working on fixing the problem? I looked up the link. Its saying its having trouble getting past a certain block. Hopefully an update will come out soon yes?

**Comment by adityapk00** [comment]
There's now a new version of Zecwallet (v0.9.15) that works around this problem on Windows. Please see the release here: https://github.com/ZcashFoundation/zecwallet/releases/tag/v0.9.15
