### ISSUE TITLE
Syncing stuck at 91.1%

### ISSUE THREAD

**Issue by raketa-sunyata** [ZcashFoundation/zecwallet#278]
Zecwallet Fullnode v0.9.13
Syncing has been being stuck at 91.1% for a day already

**Comment by adityapk00** [comment]
You are running into this issue: Please follow along here: https://github.com/zcash/zcash/issues/4620

**Comment by adityapk00** [comment]
There's now a new version of Zecwallet (v0.9.15) that works around this problem on Windows. Please see the release here: https://github.com/ZcashFoundation/zecwallet/releases/tag/v0.9.15
