### ISSUE TITLE
Windows full node not receiving any connections through Tor

### ISSUE THREAD

**Issue by kwysis** [ZcashFoundation/zecwallet#279]
I can’t get any connections when selecting Tor during setup on Windows. Tor service is running (expert bundle) during setup. I’ve tried running full node with tor service running, and without. 0 connections.

Thank you.

**Comment by kwysis** [comment]
Sorry—this is on Windows.

**Comment by adityapk00** [comment]
Did you try adding the tor nodes? Here's some additional info: https://docs.zecwallet.co/using-zecwallet/#connect-via-tor

**Comment by kwysis** [comment]
Yes, that fixed it! Thank you for that. I thought by automatically selecting tor and running tor service that it would automatically find and add onion nodes to the config file. Is your sample list the only onion nodes currently available?

**Comment by adityapk00** [comment]
Those are seed nodes. New nodes are automatically discovered via the p2p network, you just need to seed them with some existing nodes
