### ISSUE TITLE
Sync roll back

### ISSUE THREAD

**Issue by alex82361** [ZcashFoundation/zecwallet#280]
Over a few days i have restarted the Zecwallet Full node v0.9.13. every time it has gotten to 99 percent it doesn't go past it. in fact it starts to roll back. right now it is on 98.9 percent complete synced.

**Comment by adityapk00** [comment]
You are running into this issue. Please follow along there. https://github.com/zcash/zcash/issues/4620

**Comment by adityapk00** [comment]
There's now a new version of Zecwallet (v0.9.15) that works around this problem on Windows. Please see the release here: https://github.com/ZcashFoundation/zecwallet/releases/tag/v0.9.15
