### ISSUE TITLE
Why I can't send ZECs to another adress

### ISSUE THREAD

**Issue by bokobuva** [ZcashFoundation/zecwallet#281]
I downloaded the full node wallet as an alternative to send out my mining rewards from jaxx liberty wallets(2). I imported the private keys and it started to sync. The sync message stated it would take up to 6 hours but it stuck at 98.5% and stayed that way for 2 days. When I restarted the PC the sync went back to 97% then quickly to 98.2% and stuck again. I tried to send out my ZECs to the desired address and it showed me message the the transaction is successfully broadcast but the coins did not arrive, I waited the day out , restarted my PC again, initialized the full node wallet and it shows that the coins are still on the wallet (not sent).

Can anyone help me how to send out my coins ? Thank you!

**Comment by adityapk00** [comment]
Are you sure you have the latest version? A bug was fixed in Zecwallet 0.9.15, so please make sure you have the latest version.

**Comment by bokobuva** [comment]
On Monday, July 27, 2020, 01:57:52 AM GMT+2, adityapk00 <notifications@github.com> wrote:  
 
 


Are you sure you have the latest version? A bug was fixed in Zecwallet 0.9.15, so please make sure you have the latest version.

**Comment by bokobuva** [comment]
there you have it, latest version, also, it states I have -1 confirmations. that can't be good right ?
    On Monday, July 27, 2020, 01:57:52 AM GMT+2, adityapk00 <notifications@github.com> wrote:  
 
 


Are you sure you have the latest version? A bug was fixed in Zecwallet 0.9.15, so please make sure you have the latest version.

**Comment by bokobuva** [comment]
version 3000050

**Comment by adityapk00** [comment]
@bokobuva I don;t think you have the latest version, since the latest Zecwallet has version `3.1.0-rc2` and you are showing `3.0.0`.

**Comment by bokobuva** [comment]
Yes, thank you, that did the trick. Thank you very much man. Regards !
