### ISSUE TITLE
I can't send ZECs to another adress. Zecwallet lite

### ISSUE THREAD

**Issue by cbr201101** [ZcashFoundation/zecwallet#285]
Hi there. I cannot send ZECs to another adress from my Wallet Lite. It's just do not proceed on Computing Transaction screen and nothing happens... I'll waiting for an hour and there is nothing. What should i do?

**Comment by cbr201101** [comment]
Zecwallet lite version is. 1.0.14 Android OS 9

**Comment by adityapk00** [comment]
Hello - Can you please file a bug on the zecwallet mobile repo here, so we can debug it: https://github.com/zecwalletco/zecwallet-mobile/issues
