### ISSUE TITLE
Why I can't send ZECs to another adress

### ISSUE THREAD

**Issue by DmitryEkb** [ZcashFoundation/zecwallet#286]
Hello! I have Zecwallet Fullnode wallet version v0.9.15 installed. I tried to send my ZEC from t-address to t-address. Sending failed. Throws the following error: ERROR: ContextualCheckTransaction(): Sapling spend description invalid
2020-07-31 07:36:27 ERROR: AcceptToMemoryPool: ContextualCheckTransaction failed.
What to do? I ask for help

**Comment by DmitryEkb** [comment]
The wallet was installed with the following file: Zecwallet.Fullnode-0.9.15-win.zip
I use Windows 7 64bit operating system.

**Comment by secured2k** [comment]
This was found to be caused by the node not being sync'd yet.
