### ISSUE TITLE
There were problems with the new version Zecwallet.Fullnode-0.9.15-win

### ISSUE THREAD

**Issue by m0nkey88** [ZcashFoundation/zecwallet#287]
There were problems with the new version wallet Zecwallet.Fullnode-0.9.15-win.zip
OS: Windows 10 1909
Zecwallet.Fullnode-0.9.15-win.zip

after the launch of a new wallet I see a message:

**CDB: Error -30972, can't open database**

db.log
BDB1582 Open file handle: C:\Users\X\AppData\Roaming\Zcash\wallet.dat
BDB1582 Open file handle: C:\Users\X\AppData\Roaming\Zcash\database\log.0000000001
BDB0060 PANIC: fatal region error detected; run recovery
BDB2506 file wallet.dat has LSN 1/66150, past end of log at 1/167
BDB2507 Commonly caused by moving a database from one database environment
BDB2508 to another without clearing the database LSNs, or by removing all of
BDB2509 the log files from a database environment
BDB2516 DB_ENV->log_flush: LSN of 1/66150 past current end-of-log of 1/167
BDB2517 Database environment corrupt; the wrong log files may have been removed or incompatible database files imported from another environment
BDB3027 wallet.dat: unable to flush page: 6455
BDB4519 txn_checkpoint: failed to flush the buffer cache: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery

I used the manual https://docs.zecwallet.co/troubleshooting/
Editing zcash.conf add the line rescan=1 , but the wallet still doesn't work.

**Comment by adityapk00** [comment]
This sounds like a corruption of the zcash data folder somehow. You need to recover the wallet/chain folder. If you have a backup of your wallet.dat, you can replace it and have it recover.

**Comment by m0nkey88** [comment]
Zecwallet.Fullnode-0.9.14-win runs smoothly, but is not synchronized above block 903001.

**Comment by m0nkey88** [comment]
weirdly, it helped.
