### ISSUE TITLE
Error Sending Transaction

### ISSUE THREAD

**Issue by bagginsmf** [ZcashFoundation/zecwallet#289]
![bug](https://user-images.githubusercontent.com/64754405/89560117-65888480-d7cb-11ea-96ab-7aad67f980ad.jpg)

please help

Error Sending Transaction
Opid opid-97e3eeb3-44ed-4949-b02e-cd9d4b55f7b3 Failed. SendTransaction: CommitTransaction failed

There is enough money on the balance sheet. Tried wallet.dat on another wallet - same thing. what to do? Zec wallet latest version

**Comment by adityapk00** [comment]
Is your node fully synced? Also, please make sure you are using the latest version - v0.9.15

**Comment by bagginsmf** [comment]
> Is your node fully synced? Also, please make sure you are using the latest version - v0.9.15

yes. status connected. v 0/9.15   what to do?

**Comment by adityapk00** [comment]
I think you might need to rescan your zcash wallet. Please see the trouble shooting guide here: https://docs.zecwallet.co/troubleshooting/#how-to-perform-a-wallet-rescan

**Comment by adityapk00** [comment]
Are you using Windows? If so, please:
- close Zecwallet
- go to %APPDATA%/Zecwallet/bin/resources/win
- Run `zcashd.exe -rescan`

**Comment by bagginsmf** [comment]
> 
> 
> Are you using Windows? If so, please:
> 
>     * close Zecwallet
> 
>     * go to %APPDATA%/Zecwallet/bin/resources/win
> 
>     * Run `zcashd.exe -rescan`

I have two zec wallet full node wallets on two computers. I was moving wallet dat from one wallet to another. The result is the same. What does rescan have to do with it? The problem obviously lies in the very address where the money is kept.

**Comment by adityapk00** [comment]
It is likely that the wallet.dat itself is somehow corrupted or has incorrect values (maybe because of moving it across computers. It is not recommended to do that). 

To fix the wallet.dat, you need to rescan (Rescan reconstructs the wallet.dat from scratch)

**Comment by bagginsmf** [comment]
> 
> 
> It is likely that the wallet.dat itself is somehow corrupted or has incorrect values (maybe because of moving it across computers. It is not recommended to do that).
> 
> To fix the wallet.dat, you need to rescan (Rescan reconstructs the wallet.dat from scratch)

wallet dat was moved only 1 time, and then today for verification. Launched rescan. Waiting
![bug rescan](https://user-images.githubusercontent.com/64754405/89568197-cc139f80-d7d7-11ea-8888-7527987e7e76.jpg)

**Comment by adityapk00** [comment]
This will take a long time. You can follow along in the log file in %APPDATA%/Zcash/debug.log 

After the rescan is finished, you can start Zecwallet (keep the terminal zcashd.exe running) and see if it works.

**Comment by bagginsmf** [comment]
> 
> 
> This will take a long time. You can follow along in the log file in %APPDATA%/Zcash/debug.log
> 
> After the rescan is finished, you can start Zecwallet (keep the terminal zcashd.exe running) and see if it works.

the only problem with this address. on which 1 $. I am afraid that this will happen again. Because there will be large sums

**Comment by adityapk00** [comment]
I highly recommend you use the Lite wallet. Download from: www.zecwallet.co 

It doesn't download the blockchain, is super fast, and will give you a seed phrase for backup, that you can recover anywhere.

**Comment by bagginsmf** [comment]
> I highly recommend you use the Lite wallet. Download from: [www.zecwallet.co](http://www.zecwallet.co)
> 
> It doesn't download the blockchain, is super fast, and will give you a seed phrase for backup, that you can recover anywhere.

![zec lite](https://user-images.githubusercontent.com/64754405/89578314-cc676700-d7e6-11ea-8a7d-34b2f0fc271d.jpg)
Does not work. Installed on a vps server. On a virtual machine - not installed at all (an error appears)

**Comment by adityapk00** [comment]
Zecwallet lite doesn't need to be installed on a VPS or a VM. It is very lightweight, and will run on your desktop/laptop. It is even available on Android and iPhone
