### ISSUE TITLE
Failed to start zcashd

### ISSUE THREAD

**Issue by parhampe** [ZcashFoundation/zecwallet#290]
Software cannot start.
it gives me following message:
"Failed to start zcashd. Giving up! Please look at the debug.log file.

[debug.log](https://github.com/ZcashFoundation/zecwallet/files/5093184/debug.log)

Please file an issue with Zecwallet"

**Comment by glestwid** [comment]
I have the same issue on my Win10 x64

**Comment by adityapk00** [comment]
Please see my comment here: https://github.com/adityapk00/zecpaperwallet/issues/10#issuecomment-685017582

@parhampe, I think you might need to delete your params directory, it seems corrupt. Please delete ` C:\Users\parha\AppData\Roaming\ZcashParams` directory. 

Note that running the fullnode is quite technically intensive, and it can take several days to download and sync. If you want to get started quicker, I'd recommend using the light client from here: www.zecwallet.co

**Comment by parhampe** [comment]
Thanks for your suggestion. It worked.
