### ISSUE TITLE
Failed to start zcashd. Giving up!

### ISSUE THREAD

**Issue by ar-jan** [ZcashFoundation/zecwallet#293]
**Describe the bug**
Starting Zecwallet fails with `Failed to start zcashd. Giving up! Please look at the debug.log file.`

**To Reproduce**

1. Have a cursed setup (?)
2. Start Zecwallet Fullnode
3. Receive error `Failed to start zcashd. Giving up! Please look at the debug.log file.`

**Expected behavior**
Zecwallet Fullnode should start normally.

**Desktop:**

- OS: Windows 10
- Version: Zecwallet Fullnode 0.9.18

**Additional context**
I had previously run into the same problem. Because the logs didn't provide any useful information, and deleting the ZcashParams directory did not work, about a week ago I decided to completely remove both the program and wallet and start fresh with Zecwallet Fullnode 0.9.17.

I installed using the .msi, downloaded the params and the entire blockchain, and imported a private key. Everything seemed to work fine. Now I'm starting the Zecwallet again and run into the same error I had before. I updated to v0.9.18 to be sure, no difference.  Deleting the ZcashParams dir does not work (it just redownloadeds the files and then I receive the same error).

I saw a comment about a VPN maybe being problematic. I normally use a VPN, but: when I shut it down and try again, it doesn't make a difference (also, about a week ago it seemed to work fine with the VPN running).

I'm also using a custom datadir -- but this was working OK after I installed just over a week ago.

This is the debug.log:
> Sep 15 22:42:35.583  INFO main: Zcash version v4.0.0-9786156 (2020-09-09 18:26:02 -0700)
> Sep 15 22:42:35.594  INFO Init: main: Using OpenSSL version OpenSSL 1.1.1a  20 Nov 2018
> Sep 15 22:42:35.594  INFO Init: main: Using BerkeleyDB version Berkeley DB 6.2.23: (March 28, 2016)
> Sep 15 22:42:35.594  INFO Init: main: Default data directory C:\Users\Arjan\AppData\Roaming\Zcash
> Sep 15 22:42:35.594  INFO Init: main: Using data directory D:\MyAppData\Zcash
> Sep 15 22:42:35.594  INFO Init: main: Using config file D:\MyAppData\Zcash\zcash.conf
> Sep 15 22:42:35.594  INFO Init: main: Using at most 125 connections (2048 file descriptors available)
> Sep 15 22:42:35.594  INFO Init: main: Using 6 threads for script verification
> Sep 15 22:42:35.594  INFO main: scheduler thread start
> Sep 15 22:42:35.595  INFO Init: main: Loading Sapling (Spend) parameters from C:\Users\Arjan\AppData\Roaming\ZcashParams\sapling-spend.params
> Sep 15 22:42:35.595  INFO Init: main: Loading Sapling (Output) parameters from C:\Users\Arjan\AppData\Roaming\ZcashParams\sapling-output.params
> Sep 15 22:42:35.595  INFO Init: main: Loading Sapling (Sprout Groth16) parameters from C:\Users\Arjan\AppData\Roaming\ZcashParams\sprout-groth16.params
> Sep 15 22:42:36.872  INFO Init: main: Loaded Sapling parameters in 1.276998s seconds.
> Sep 15 22:42:36.877  INFO Init: main: libevent: getaddrinfo: nodename nor servname provided, or not known
> Sep 15 22:42:36.877  INFO Init: main: Binding RPC on address ::1 port 8232 failed.
> Sep 15 22:42:36.878  INFO Init: main: HTTP: creating work queue of depth 16
> Sep 15 22:42:36.878  INFO Init: main: Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
> Sep 15 22:42:36.878  INFO Init: main: HTTP: starting 4 worker threads
> Sep 15 22:42:36.878  INFO Init: main: Using wallet wallet.dat
> Sep 15 22:42:36.878  INFO Init: main: init message: Verifying wallet...
> Sep 15 22:42:36.878  INFO Init: main: CDBEnv::Open: LogDir=D:\MyAppData\Zcash\database ErrorFile=D:\MyAppData\Zcash\db.log
> Sep 15 22:42:36.888  INFO Init: main: Bound to [::]:8233
> Sep 15 22:42:36.888  INFO Init: main: Bound to 0.0.0.0:8233
> Sep 15 22:42:36.888  INFO Init: main: Cache configuration:
> Sep 15 22:42:36.888  INFO Init: main: * Using 2.0MiB for block index database
> Sep 15 22:42:36.888  INFO Init: main: * Using 120.0MiB for chain state database
> Sep 15 22:42:36.888  INFO Init: main: * Using 328.0MiB for in-memory UTXO set
> Sep 15 22:42:36.888  INFO Init: main: init message: Loading block index...
> Sep 15 22:42:36.888  INFO Init: main: Opening LevelDB in D:\MyAppData\Zcash\blocks\index
> Sep 15 22:42:36.911  INFO Init: main: Opened LevelDB successfully
> Sep 15 22:42:36.911  INFO Init: main: Opening LevelDB in D:\MyAppData\Zcash\chainstate
> Sep 15 22:42:36.928  INFO Init: main: Opened LevelDB successfully
> Sep 15 22:43:00.984  INFO Init: main: LoadBlockIndexDB: last block file = 175
> Sep 15 22:43:00.984  INFO Init: main: LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=3352, size=40816343, heights=959400...963068, time=2020-09-03...2020-09-06)
> Sep 15 22:43:00.984  INFO Init: main: Checking all blk files are present...
> Sep 15 22:43:01.138  INFO Init: main: LoadBlockIndexDB: transaction index disabled
> Sep 15 22:43:01.138  INFO Init: main: LoadBlockIndexDB: insight explorer disabled
> Sep 15 22:43:01.138  INFO Init: main: LoadBlockIndexDB: light wallet daemon disabled
> Sep 15 22:43:01.568  INFO Init: main: LoadBlockIndexDB: hashBestChain=00000000002cda44d318a7e435ab658e5364ea66fd62e8ec035ff102d627003e height=963068 date=2020-09-06 20:25:17 progress=0.986236
> Sep 15 22:43:01.570  INFO Init: main: init message: Rewinding blocks if needed...
> Sep 15 22:43:32.460  INFO Init: main: init message: Verifying blocks...
> Sep 15 22:43:32.460  INFO Init: main: Verifying last 288 blocks at level 3
> Sep 15 22:43:33.160  INFO Init: main: No coin database inconsistencies in last 289 blocks (1829 transactions)
> Sep 15 22:43:33.175  INFO Init: main:  block index           56287ms
> Sep 15 22:43:33.175  INFO Init: main: init message: Loading wallet...
> Sep 15 22:43:33.180  INFO Init: main: nFileVersion = 3010050
> Sep 15 22:43:33.180  INFO Init: main: Keys: 102 plaintext, 0 encrypted, 102 w/ metadata, 102 total
> Sep 15 22:43:33.180  INFO Init: main: ZKeys: 1 plaintext, 0 encrypted, 1 w/metadata, 1 total
> Sep 15 22:43:33.186  INFO Init: main:  wallet                   11ms
> Sep 15 22:43:33.186  INFO Init: main: init message: Rescanning...
> Sep 15 22:43:33.186  INFO Init: main: Rescanning last 53039 blocks (from block 910029)...

db.log says:
> BDB2506 file wallet.dat has LSN 4/603735, past end of log at 1/560680
> BDB2507 Commonly caused by moving a database from one database environment
> BDB2508 to another without clearing the database LSNs, or by removing all of
> BDB2509 the log files from a database environment
> BDB2516 DB_ENV->log_flush: LSN of 4/603735 past current end-of-log of 1/560680
> BDB2517 Database environment corrupt; the wrong log files may have been removed or incompatible database files imported from another environment
> BDB3027 wallet.dat: unable to flush page: 23
> BDB0060 PANIC: fatal region error detected; run recovery
> BDB3015 wallet.dat: write failed for page 36
> BDB3027 wallet.dat: unable to flush page: 36
> BDB0060 PANIC: fatal region error detected; run recovery
> [... many repetitions omitted]
> BDB0060 PANIC: fatal region error detected; run recovery
> BDB1581 File handles still open at environment close
> BDB1582 Open file handle: D:\MyAppData\Zcash\wallet.dat
> BDB1582 Open file handle: D:\MyAppData\Zcash\database\log.0000000001
> BDB0060 PANIC: fatal region error detected; run recovery
> BDB2506 file wallet.dat has LSN 1/454, past end of log at 1/167
> BDB2507 Commonly caused by moving a database from one database environment
> BDB2508 to another without clearing the database LSNs, or by removing all of
> BDB2509 the log files from a database environment
> BDB2516 DB_ENV->log_flush: LSN of 1/454 past current end-of-log of 1/167
> BDB2517 Database environment corrupt; the wrong log files may have been removed or incompatible database files imported from another environment
> BDB3027 wallet.dat: unable to flush page: 13
> BDB4519 txn_checkpoint: failed to flush the buffer cache: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
> BDB0060 PANIC: fatal region error detected; run recovery

So something seems to have gone wrong with the database, but I have no idea how.

I also tried running `zcashd.exe --addnode=mainnet.z.cash --addnode=lightwalletd.zecwallet.co` manually as suggested [here](https://github.com/adityapk00/zecpaperwallet/issues/10#issuecomment-685017582). When running it on cmd.exe, zcashd.exe just exits after about one minute. When running on PowerShell, there is an error after about a minute:
> Thank you for running a mainnet zcashd v4.0.0 node! You're helping to strengthen the network and contributing to a social good :)
> In order to ensure you are adequately protecting your privacy when using Zcash, please see <https://z.cash/support/security/>.
> Since starting this node 56 seconds ago:
> - You have validated 792 transactions!
> Init message: Verifying blocks...
> ['zcash-cli.exe stop' to exit] [Set 'showmetrics=0' to hide]
> Assertion failed!
> Program: C:\Users\Username\AppData\Local\Programs\zecwallet\resources\bin\win\zcashd.exe
> File: wallet/wallet.cpp, Line 1095
> Expression: (nd->witnessHeight == -1) || (nd->witnessHeight == indexHeight - 1)

Any ideas how to fix this?

**Comment by adityapk00** [comment]
It appears that you are running into this error: https://github.com/zcash/zcash/issues/4301 

The problem is with the underlying zcashd, which has not been fixed. Unfortunately the only solution to this is to run `zcashd.exe -reindex` once, but that will take several hours (or days) to reindex the entire blockchain. 

Alternately, you can switch to using the lite client, which you can use without needing to download the blockchain (www.zecwallet.co)

**Comment by ar-jan** [comment]
I tried that, but unfortunately the reindexing also errored out at 91%.


> Sep 16 22:32:03.426  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000000281f12690c34322930d1942d1734ca960aed7deb4fbe3506233211 height=694862 bits=469909392 log2_work=57.232931 tx=5763815 date=2020-01-16 21:48:14 progress=0.621004 cache=300.8MiB(36754tx)
> Sep 16 22:32:04.250  INFO ProcessNewBlock: main: Corruption: block checksum mismatch
> Sep 16 22:32:04.259  INFO ProcessNewBlock: main: *** System error while flushing: Database corrupted
> Sep 16 22:32:04.466 ERROR ProcessNewBlock: main: ProcessNewBlock: ActivateBestChain failed
> Sep 16 22:32:04.466  INFO main: Loaded 6408 blocks from external file in 157338ms
> Sep 16 22:32:04.473  INFO main: Reindexing block file blk00161.dat...
> Sep 16 22:32:04.530  INFO main: tor: Thread interrupt
> Sep 16 22:32:04.532  INFO main: torcontrol thread exit
> Sep 16 22:32:04.534  INFO main: scheduler thread interrupt
> Sep 16 22:32:04.534  INFO main: opencon thread interrupt
> Sep 16 22:32:04.534  INFO main: msghand thread interrupt
> Sep 16 22:32:04.535  INFO main: addcon thread interrupt
> Sep 16 22:32:04.545  INFO main: txnotify thread interrupt
> Sep 16 22:32:04.560  INFO main: net thread interrupt
> Sep 16 22:32:04.564  INFO Shutdown: main: StopRPC: waiting for async rpc workers to stop
> Sep 16 22:32:04.565  INFO Shutdown: main: StopNode()
> Sep 16 22:32:04.605  INFO Shutdown: main: Corruption: block checksum mismatch
> Sep 16 22:32:04.605  INFO Shutdown: main: *** System error while flushing: Database corrupted
> Sep 16 22:32:04.943  INFO Shutdown: main: done

Should I try this again and hope for better luck?

**Comment by adityapk00** [comment]
In addition to the underlying zcashd bug, it looks like your data directory is corrupted. You will need to delete everything in the %APPDATA%/Zcash directory (please backup your wallet.dat first), and then sync the blockchain again from scratch.

**Comment by ar-jan** [comment]
Since this was the second time this happened, after starting from scratch, I'm now giving it a try on a Linux machine to see if that works better for me.

**Comment by adityapk00** [comment]
If this has happened to you multiple times, it may indicate a hard disk failure or bad sectors.

**Comment by ar-jan** [comment]
Hmm, chkdsk says the drive is fine.

**Comment by hurr1cane78** [comment]
same crap
