### ISSUE TITLE
[Feature request] Add coin controll to be able to set custom change address

### ISSUE THREAD

**Issue by skironDotNet** [ZcashFoundation/zecwallet#294]
I use wallet with imported addresses from bip39 tool to be able to recover funds in case I lose wallet.dat, and I noticed I can't set custom change address and auto generated address is used tied to wallet.dat...
Other way of handling it would a use od deterministic wallet with ability to export and import private HD key

**Comment by adityapk00** [comment]
Closing this, since this is not in control of Zecwallet, and will need to be implemented in zcashd. Please feel free to open an issue there if you like.
