### ISSUE TITLE
Zec wallet download

### ISSUE THREAD

**Issue by cmechen2278** [ZcashFoundation/zecwallet#296]
Hi, I am really struggling to download Zec wallet full node. I am stuck around 15% now for a week? I have plenty of space for files and 8G ram.  I followed all instructions and has downloaded 15% of the blockchain. Re-started 5 times, but still no further???

**Comment by adityapk00** [comment]
Please see our troubleshooting docs if you haven't already: https://docs.zecwallet.co/troubleshooting/#my-node-isnt-syncing-or-is-slow-to-sync

You may need to open ports on your firewall

I'd recommend using the lite wallet if you don't absolutely need a full node. It's much much faster and syncs in minutes: www.zecwallet.co
