### ISSUE TITLE
[ERROR] CWallet::GenerateNewKey(): AddKey failed

### ISSUE THREAD

**Issue by D3vRandom** [ZcashFoundation/zecwallet#297]
Upgraded from a previous version of your wallet and now when I replace the wallet.dat file in the Zcash directory the wallet doesn't start

BDB2506 file wallet.dat has LSN 1/175835, past end of log at 1/167
BDB2507 Commonly caused by moving a database from one database environment
BDB2508 to another without clearing the database LSNs, or by removing all of
BDB2509 the log files from a database environment
BDB2516 DB_ENV->log_flush: LSN of 1/175835 past current end-of-log of 1/167
BDB2517 Database environment corrupt; the wrong log files may have been removed or incompatible database files imported from another environment
BDB3027 wallet.dat: unable to flush page: 13
BDB4519 txn_checkpoint: failed to flush the buffer cache: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery

**Comment by adityapk00** [comment]
This seems to be an error with zcashd, please file a bug with the zcashd project: https://github.com/zcash/zcash

In the meanwhile, you can try to start zcashd.exe manually.

You can find the `zcashd.exe` executable in `resources/bin/win/zcashd.exe` folder of where you install zecwallet. 
Try 
`zcashd.exe -reindex` or `zcashd.exe -rescan` and see if it helps.

**Comment by D3vRandom** [comment]
> This seems to be an error with zcashd, please file a bug with the zcashd project: https://github.com/zcash/zcash
> 
> In the meanwhile, you can try to start zcashd.exe manually.
> 
> You can find the `zcashd.exe` executable in `resources/bin/win/zcashd.exe` folder of where you install zecwallet.
> Try
> `zcashd.exe -reindex` or `zcashd.exe -rescan` and see if it helps.

So I followed your instructions but still the same error happens once I start the wallet. For some reason if I start the GUI without the wallet.dat a new one is generated and the GUI proceeds to open, else if the original wallet.dat is in the zcash folder then the wallet freezes before opening.

**Comment by adityapk00** [comment]
Yup - `zcashd` will create a new, empty wallet if you start without one. (Note that zecwallet just spawns `zcashd` underneath, which is handling the wallet. I would try `zcashd.exe -salvagewallet`

Please see a similar issue on zcash: https://github.com/zcash/zcash/issues/1694

If it still doesn't work, I would encourage you to file an issue with zcashd. There are experts there that can help. 

I would also encourage you to use zecwallet lite. That has an actual seed phrase that you can backup, so you won't run into these kinds of issues in the future.

**Comment by D3vRandom** [comment]
> Yup - `zcashd` will create a new, empty wallet if you start without one. (Note that zecwallet just spawns `zcashd` underneath, which is handling the wallet. I would try `zcashd.exe -salvagewallet`
> 
> Please see a similar issue on zcash: [zcash/zcash#1694](https://github.com/zcash/zcash/issues/1694)
> 
> If it still doesn't work, I would encourage you to file an issue with zcashd. There are experts there that can help.
> 
> I would also encourage you to use zecwallet lite. That has an actual seed phrase that you can backup, so you won't run into these kinds of issues in the future.

Thanks I'll do that, although I'm not sure why this is happening. I use this wallet on May 26 2020. I don't know why having this wallet offline for 4 months has caused these issues of incompatibility

**Comment by adityapk00** [comment]
Note that I'm not an expert, but I think what has happened is that the `wallet.dat` is somehow corrupted. I don't think it is a compatibility issue.

**Comment by D3vRandom** [comment]
> Note that I'm not an expert, but I think what has happened is that the `wallet.dat` is somehow corrupted. I don't think it is a compatibility issue.

Zcashd.exe runs perfectly in the CMD although only in the GUI does it present an issue. I just started the salvage and zcashd is loading fine so far just doing a rescan now.

**Comment by adityapk00** [comment]
Great! If it completes successfully, just let `zcashd.exe` running in a window and start Zecwallet, and it will connect to the existing `zcashd`. 

I will recomment using a lite wallet instead of this full node. Using the full node is cumbersome and error prone, and you can run into issues like this. Using a lite wallet will give you a seed phrase that you can backup easily, so you won't lose funds like you might have here. www.zecwallet.co to check out the lite wallet.

**Comment by D3vRandom** [comment]
Prefect yeah I do plan on using it, I just need to extract my private keys or get a way of making a transfer to a new address. 

One more thing is that the export all address in under the file tab doesn't export the change address for taddresses it only exports current receiving addresses. Not sure if this is a known issue.

**Comment by adityapk00** [comment]
Yes - the t-addresses in the full node are not generated via a HD key (they are random), so the wallet can't really track all of them, even though the wallet is trying its best.
