### ISSUE TITLE
rip wallet.dat

### ISSUE THREAD

**Issue by undertheStrarlight** [ZcashFoundation/zecwallet#300]
it happened suddenly..  HUH? 
used the app as usual, no backup / private key available.. only 'damaged' wallet.dat file 
I think only way is get the private key from the “damaged”(as zcashd says) wallet.dat 
Can you help me? For reward. INCREDIBLY need this money 

![wallet](https://user-images.githubusercontent.com/73359466/97036585-77cfbe80-1581-11eb-83b8-d3c424bd4cd6.jpg)
[db.log](https://github.com/ZcashFoundation/zecwallet/files/5430985/db.log)
[debug.log](https://github.com/ZcashFoundation/zecwallet/files/5430987/debug.log)

**Comment by adityapk00** [comment]
`Error: wallet.dat corrupt, salvage failed` -> I think this is pretty bad, if you don't have a backup. 

If you have the original wallet.dat, you can try emailing it to me and I can see what I can do, but I don't think it is recoverable. My email is aditya -at- zecwallet -dot- co

**Comment by rex4539** [comment]
https://forum.zcashcommunity.com/t/recovering-funds-from-wallet-dat/
