### ISSUE TITLE
Default fee is incorrectly projected resulting in insufficient funds when attempting to send maximum

### ISSUE THREAD

**Issue by Troglodactyl** [ZcashFoundation/zecwallet#302]
The default fee value for z_sendmany in the full node is 0.0001 but the Zecwallet treats it as 0.00001 both in the send menu and in the "Confirm transaction" preview screen.

    Go to 'Send'
    Select a transparent address with a balance under 'Send From'
    Paste a zAddress into "To"
    Click on the up arrow to the right of the amount field to send maximum balance.
    Click Send
    The preview will be displayed showing the fee and amount which sum to the full available balance.
    Click confirm
    Error will indicate insufficient transparent funds

Fees should be accurately shown prior to confirming the operation, and the "send max" helper should properly account for fees.

This appears to be hard-coded in zecwallet/app/utils/utils.js:113, probably because the zcash full node doesn't provide a way to retrieve its default fees.  If the full node can't have this functionality added to allow accurate transaction previews I'd suggest overriding the default fee value when creating transactions from zecwallet.

**Comment by adityapk00** [comment]
Thanks for reporting this! I'll work on it now .
