### ISSUE TITLE
Incorrect tx fee when sending ZEC from t-addr to z-addr

### ISSUE THREAD

**Issue by nighthawk24** [ZcashFoundation/zecwallet#303]
Try sending a t-addr to z-addr transaction, the fee in the UI shows as 0.00001 per ZIP-313 but the actual transaction that is broadcast sets the old fee of 0.0001

Environment: MacOS 11.1
Zecwallet Fullnode v0.9.24

**Comment by adityapk00** [comment]
I just tried this, and it seems like the correct fee (`0.00001 ZEC`) is being sent, but some block explorers are reporting the wrong fee. 

Compare:
Wrong fee: https://zcha.in/transactions/c589eccdaae8c45e9b15e0ca0198601a1038cfa624c5f1151040a73ef6f12ec7
Correct: https://blockchair.com/zcash/transaction/c589eccdaae8c45e9b15e0ca0198601a1038cfa624c5f1151040a73ef6f12ec7

The actual fee paid is correct (`0.00001 ZEC`)

**Comment by nighthawk24** [comment]
Maybe a good idea to switch to blockchair.com going forward?

**Comment by gmale** [comment]
We switched to block chair in our internal wallets.

**Comment by nighthawk24** [comment]
@adityapk00 this issue still affects users, would you consider switching to https://zcashblockexplorer.com
https://zcashblockexplorer.com/transactions/c589eccdaae8c45e9b15e0ca0198601a1038cfa624c5f1151040a73ef6f12ec7

Zcash Block Explorer is a community funded, privacy preserving transaction explorer.
