### ISSUE TITLE
Failed to start zcashd. Giving up! Please look at the debug.log file.

### ISSUE THREAD

**Issue by Tolics** [ZcashFoundation/zecwallet#307]
Good afternoon. Installed Zecwallet.Fullnode.0.9.24. msi. When opening the wallet, a message appeared: "Failed to start zcashd. Giving up! Please look at the debug.log file.
Please file an issue with Zecwallet". The file contains the following : "Jan 13 22: 35:10.494 INFO main: Zcash version v4.2.0 (2020-12-21 20:08:33 +0000)
Jan 13 22:35:10.502 INFO Init: main: Using BerkeleyDB version Berkeley DB 6.2.23: (March 28, 2016)
Jan 13 22: 35:10.502 INFO Init: main: Default data directory C:\Users\пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ\AppData\Roaming\Zcash
Jan 13 22: 35:10.502 INFO Init: main: Using data directory C:\Users\пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ\AppData\Roaming\Zcash
Jan 13 22: 35:10.502 INFO Init: main: Using config file C:\Users\пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ\AppData\Roaming\Zcash\zcash.conf
Jan 13 22:35:10.502 INFO Init: main: Using at most 125 connections (2048 file descriptors available)
Jan 13 22:35:10.502 INFO Init: main: Using 2 threads for script verification
Jan 13 22:35:10.502 INFO main: scheduler thread start
Jan 13 22: 35:10.503 INFO Init: main: Loading Sapling (Spend) parameters from C:\Users\пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ\AppData\Roaming\ZcashParams\sapling-spend.params
Jan 13 22: 35:10.503 INFO Init: main: Loading Sapling (Output) parameters from C:\Users\пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ\AppData\Roaming\ZcashParams\sapling-output.params
Jan 13 22: 35: 10.503 INFO Init: main: Loading Sapling (Sprout Groth16) parameters from C:\Users\пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ\AppData\Roaming\ZcashParams\sprout-groth16.params
Jan 13 22:35:12.704 INFO Init: main: Loaded Sapling parameters in 2.200275s seconds.
Jan 13 22:35:12.722 INFO Init: main: libevent: getaddrinfo: nodename nor servname provided, or not known
Jan 13 22:35:12.722 INFO Init: main: Binding RPC on address ::1 port 8232 failed.
Jan 13 22:35:12.722 INFO Init: main: HTTP: creating work queue of depth 16
Jan 13 22:35:12.723 INFO Init: main: Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
Jan 13 22:35:12.723 INFO Init: main: HTTP: starting 4 worker threads
Jan 13 22:35:12.724 INFO Init: main: Using wallet wallet.dat
Jan 13 22:35:12.724 Init INFO: main: init message: Verifying wallet...
Jan 13 22:35:12.725 INFO Init: main: CDBEnv::Open: LogDir=C:\Users\PPP\AppData\Roaming\zcash for\database ErrorFile=C:\Users\PPP\AppData\Roaming\zcash for\db.log
Jan 13 22:35:13.267 INFO Init: main: Bound to [::]:8233
Jan 13 22:35:13.267 INFO Init: main: Bound to 0.0.0.0:8233
Jan 13 22:35:13.267 INFO Init: main: Cache configuration:
Jan 13 22:35:13.267 INFO Init: main: * Using 2.0MiB for block index database
Jan 13 22:35:13.267 INFO Init: main: * Using 120.0MiB for chain state database
Jan 13 22:35:13.267 INFO Init: main: * Using 328.0MiB for in-memory UTXO set
Jan 13 22: 35: 13.267 INFO Init: main: init message: Loading block index ...
Jan 13 22:35: 13.269 INFO Init: main: Opening LevelDB in C:\Users\пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ\AppData\Roaming\Zcash\blocks\index
Jan 13 22: 35:13.271 INFO Init: main: IO error: C:\Users\пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ\AppData\Roaming\Zcash\blocks\index\LOCK: Could not lock file.
Jan 13 22:35:13.273 INFO Init: main: : Error opening block database.
Please restart with -reindex to recover.
Jan 13 22:35:13.273 INFO Init: main: Aborted block database rebuild. Exiting.
Jan 13 22:35:13.274 INFO Shutdown: main: StopRPC: waiting for async rpc workers to stop
Jan 13 22:35:13.274 INFO Shutdown: main: StopNode()
Jan 13 22:35:13.275 INFO main: scheduler thread interrupt
Jan 13 22:35:13.275 INFO Shutdown: main: done". 
Please tell me what to do that would work?

**Comment by nighthawk24** [comment]
Have you tried reindexing? https://docs.zecwallet.co/troubleshooting/

**Comment by Tolics** [comment]
Good afternoon. Yes, in the end, I figured it out myself. After multiple attempts to run the reindex, I ran it. Immediately made the import of private keys. The reindex eventually hovered at 17%. When restarting, the error began to appear again and the wallet did not start. The saved private keys I exported to in a 100% synchronized wallet on another computer. And the coins appeared.
