### ISSUE TITLE
Witness Height Assertion Failed

### ISSUE THREAD

**Issue by PRabahy** [ZcashFoundation/zecwallet#311]
I keep getting a "Could not connect to zcashd" error shortly after launching ZECWallet. I tried to trouble shoot it a little bit and got

```
C:\Users\USERNAME>C:\Users\USERNAME\AppData\Local\Programs\zecwallet\resources\bin\win\zcashd.exe
Assertion failed: (nd->witnessHeight == -1) || (nd->witnessHeight == indexHeight - 1), file wallet/wallet.cpp, line 1116
```
I'm going to try a reindex to see if that fixes it.

Also, I hope I'm using the correct place to report a bug. https://github.com/ZcashFoundation/zecwallet/issues/new/choose didn't have bug report as an option.

**Comment by adityapk00** [comment]
You're running into this issue in the underlying `zcashd` https://github.com/zcash/zcash/issues/4301

You need to reindex and then launch again as you're already doing.

**Comment by PRabahy** [comment]
Confirmed that reindex fixed it.
