### ISSUE TITLE
Change the storage path of downloaded blocks

### ISSUE THREAD

**Issue by daniellocust** [ZcashFoundation/zecwallet#313]
The full node version needs to download all blcoks to local disk. In windows, the store path is %appdata%\Roaming\Zcash\blocks. But if the system crashes, it needs to download all blocks again. So, it's better to enable relocate the storage path.

**Comment by adityapk00** [comment]
You can change the storage path by including the "datadir" option in zcash.conf

**Comment by daniellocust** [comment]
> You can change the storage path by including the "datadir" option in zcash.conf

Thanks！
