### ISSUE TITLE
Bug report: Sent transaction is not appearing in transaction history.

### ISSUE THREAD

**Issue by nuttycom** [ZcashFoundation/zecwallet#318]
A z->t transaction that I sent is showing up in a block explorer, but doesn't appear in the transaction history UI.

**Comment by adityapk00** [comment]
The problem is that zcashd doesn't store outgoing z transactions, so Zecwallet Fullnode has no way to get it. Zecwallet could store the outgoing transactions itself, but that has privacy/security implications. 

See also https://github.com/ZcashFoundation/zecwallet/issues/255

**Comment by nuttycom** [comment]
Oh geez. I guess I should assign this one to myself. :) Thanks @adityapk00.
