### ISSUE TITLE
Bug report: Zecwallet FullNode MacOS (.dmg) can't be opened 

### ISSUE THREAD

**Issue by awasunyin** [ZcashFoundation/zecwallet#320]
I've downloaded the .dmg of the Zecwallet FullNode for MacOS from [this page](https://www.zecwallet.co/fullnode.html#download). When trying to open this application locally, the following windows shows up: 
<img width="424" alt="Screen Shot 2021-05-11 at 15 25 56" src="https://user-images.githubusercontent.com/11296013/117823016-527c7680-b26d-11eb-95df-6a14edc7399d.png">

---

Go to 'https://www.zecwallet.co/fullnode.html#download'
Click on Download 'MACOS (.dmg)' --> then click on the Zecwallet Fullnode.app
See error: 
<img width="424" alt="Screen Shot 2021-05-11 at 15 25 56" src="https://user-images.githubusercontent.com/11296013/117823232-86f03280-b26d-11eb-8511-d9abe05af56f.png">

I'm on Desktop:
OS: macOS Catalina Version 10.15.7 (19H1030)
Browser safari (just for the download)
Version 14.1 (15611.1.21.161.5, 15611)

**Comment by adityapk00** [comment]
Thanks for reporting this. It was due to an expired certificate, which is now fixed. 

https://github.com/ZcashFoundation/zecwallet/releases/tag/v1.6.1
