### ISSUE TITLE
start the fullnode wallet and it show "disconnected Method not found"

### ISSUE THREAD

**Issue by ad1439** [ZcashFoundation/zecwallet#326]
![屏幕截图(49)](https://user-images.githubusercontent.com/91398860/134790612-cada7a36-e50b-4e8b-a343-25ad64dba612.png)
Sep 26 10:02:05.989  INFO main: tor: Thread interrupt
Sep 26 10:02:05.989  INFO main: scheduler thread interrupt
Sep 26 10:02:05.990  INFO main: opencon thread interrupt
Sep 26 10:02:05.990  INFO main: addcon thread interrupt
Sep 26 10:02:05.990  INFO main: torcontrol thread exit
Sep 26 10:02:05.990  INFO main: UpdateTip: new best hash=0000000069a58c5375f3da75dc0530f00e801e80b8d415805098aab14a9d45a5 height=9651 bits=486681911 log2_work=43.235392 tx=80567 date=2016-11-13 14:12:57 progress=0.002975 cache=54.1MiB(50226tx)
Sep 26 10:02:05.991  INFO main: msghand thread interrupt
Sep 26 10:02:06.034  INFO main: net thread interrupt
Sep 26 10:02:06.377  INFO main: txnotify thread interrupt

**Comment by ufobbs** [comment]
+1

**Comment by ChileBob** [comment]
+1

Using v1.7.3 to connect to zcashd v4.5.0, debug.log says 'rustzcash::address_ffi: Zcash Sapling addresses are not supported'.

**Comment by adityapk00** [comment]
Thanks for reporting this. New build with fix coming...
