### ISSUE TITLE
Request: Bump zcashd dependency to v4.6.0-2 and release ZecWallet v1.7.7

### ISSUE THREAD

**Issue by nighthawk24** [ZcashFoundation/zecwallet#353]
TL;DR: Release 4.6.0 and 4.6.0-1 zcashd nodes will reach End of Service on or about April 13th, 2022. Prior to that time, all nodes must upgrade to 4.6.0-2 to avoid service interruptions.

[https://electriccoin.co/blog/new-release-4-6-0-2/](https://electriccoin.co/blog/new-release-4-6-0-2/)

**Comment by adityapk00** [comment]
Release v1.7.7 with zcashd v4.6.0-2
