### ISSUE TITLE
Zecwallet full node 1.8.2 does not start on Windows 10/x64

### ISSUE THREAD

**Issue by vovodroid** [ZcashFoundation/zecwallet#366]
Dixi:

![image](https://user-images.githubusercontent.com/8691781/175786055-a4278daa-7fd4-4c6c-b08f-5e150719fd33.png)

Zcashd started:

![image](https://user-images.githubusercontent.com/8691781/175786136-dea0fba1-d60c-4db9-ba44-3b5fdca014b5.png)

**Comment by vovodroid** [comment]
Still in beta 2

**Comment by adityapk00** [comment]
Can you paste your zcash.conf here please?

**Comment by vovodroid** [comment]
```
server=1
rpcuser=zecwallet
rpcpassword=********
ibdskiptxverification=1
datadir=D:\Zcash
```

**Comment by adityapk00** [comment]
I suspect the datadir= is causing some issues. Let me investigate
