### ISSUE TITLE
Failes to start - permanent error "Please run 'zcashd-wallet-tool' to create your wallet first..."

### ISSUE THREAD

**Issue by vovodroid** [ZcashFoundation/zecwallet#378]
Fresh setup 1.8.3 on Win10/x64, no wallet.dat run zcashd:

![image](https://user-images.githubusercontent.com/8691781/182906924-5346d395-77da-4a52-a8d6-7fceb1f86ba8.png)

Next run ZecWallet with error:

![image](https://user-images.githubusercontent.com/8691781/182906742-0083035e-868c-470c-904e-95ae33c9a86f.png)

Run zcashd-wallet-tool:

![image](https://user-images.githubusercontent.com/8691781/182907332-9475ef92-6d6f-4ab5-a9e6-a24e6756bec9.png)

Still error

![image](https://user-images.githubusercontent.com/8691781/182906742-0083035e-868c-470c-904e-95ae33c9a86f.png)

P.S.: my data dir is not in \AppData\Roaming\Zcash

**Comment by alex138038** [comment]
Use the following commands: 
1. zcash-cli.exe z_getnewaccount
2. zcash-cli.exe z_getaddressforaccount 0

**Comment by vovodroid** [comment]
Well, I run

```
./zcash-cli.exe z_getnewaccount
{
  "account": 0
}
./zcash-cli.exe z_getaddressforaccount 0
{
  "account": 0,
  "address": "u154xgpsexy7anzswggne7yeetgs9d4ngmwa4645uwygpj9dxcx4ajz5yjsx59stwm5my9j7xyuj67ec2ntyhm7707vvxf86tkd6t7kxhnte57j0632fuu9s5hp39jsvqwkye4fg065334a8y7ngfnvs34df3fmx0mc0x7kdcrggp8ph54dl0ytl4vgxn4qs0m2ldlfg24ax7szctv57s",
  "diversifier_index": 0,
  "receiver_types": [
    "p2pkh",
    "sapling",
    "orchard"
  ]
}

```
Now Zecwallet starts, but main windows is empty and there is no reaction on clicks on items in left menu (Dashboard, etc).

**Comment by alex138038** [comment]
This is a problem for all users, the developer does not comment on this problem:( The only option is to use the wallet via the command line zcash-cli.exe
Use the command: zcash-cli.exe help - this is a list of all commands.
As an ordinary user, two commands will be enough:
1. zcash-cli.exe listaddressgroupings - a list of your addresses and their balance.
2. zcash-cli.exe z_sendmany - money transfer.

**Comment by adityapk00** [comment]
Unfortunately this is not something Zecwallet can fix. Remember that the Zecwallet Fullnode is just a UI interface - your wallet lives in zcashd. All of the steps here are needed by `zcashd`, and there are no RPC methods to do that (yet), so Zecwallet can't run the zcashd-wallet-tool for you yet. 

Closing this now, and will fix if zcashd adds that capability in the future
