### ISSUE TITLE
Error invoking remote method 'doRPC_IPC': NO_CONNECTION 1.85

### ISSUE THREAD

**Issue by aleksey988** [ZcashFoundation/zecwallet#395]
when i start zcashd 1.85 it scans then closes.when i start older vesions it says version deprecated.please help

**Comment by yes312** [comment]
I installed old version(1.7.5.0 in my case). It is not synchronized, but I can see privat t-key.
Then I installed jaxx wallet for my phone and used "Import from paper wallet"
Profit!

**Comment by adityapk00** [comment]
Updated Zecwallet and the binaries.

**Comment by bolexator** [comment]
This is a complete dead end. For more than half a year it is impossible to start the wallet, not to withdraw funds. The proposed methods for launching the program do not work.
