### ISSUE TITLE
Zecwallet Fullnode Stuck On "Loading..." Forever

### ISSUE THREAD

**Issue by realizecondition** [ZcashFoundation/zecwallet#396]
Running Windows 10 64 bit. I grabbed the .msi file from the website here:

https://zecwallet.co/fullnode.html#download

Verified correct HASH:
7C4008EBE05CE42CB687C8EC72387CC606FF0BFBC49695FAA5F604CC8E2AF17D

Ran the .msi file. Everything seemed fine. It didn't prompt me for anything like an install path or anything like that. In the end an icon appeared on the desktop.

When I double click on it, it opens up an application with a large "Loading..." with the ZecWallet icon in the middle but nothing else happens even after several hours. It just stays on Loading...

I went here for debugging instructions:
https://docs.zecwallet.co/troubleshooting/

But there isn't even a "%HOMEPATH%\AppData\Roaming\Zcash\" directory. I think there should be a zcashd process but I'm not able to find one in the Task Manager either.

I have tried to uninstall and reinstall completely again and still the same problem happens. There's no error report or anything - just the Loading... screen is all I see.
![zcash-failure](https://user-images.githubusercontent.com/120234564/210701822-46f2480e-77f7-47e7-89c5-8f119a2305e4.jpg)

Any idea what I should try or any information I can include?

**Comment by LukeWheeldon** [comment]
Same here. Loading... with no details as to what is going on, what may be blocking, etc.

**Comment by dandare76** [comment]
This happens because the current version of the node for Windows has been deprecated. Only Linux versions work.

I have tried asking when the new Windows version will be ready, but the developer team gave no response.

**Comment by adityapk00** [comment]
I just release updated versions of Zecwallet and zcashd that should now work!

**Comment by andkom** [comment]
1.8.7 on Mac some issue...
