### ISSUE TITLE
Utilize Zcash URI

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zecwallet#50]
Reproducibility: always

Steps:
Click on a Zcash URI eg. `zcash:zs1du0cfxytxjjauyr2lv68qd6jd2d4shcllt5y60fx2hhdlhq4c9r6a9kttfdynpgkygpv2asu5ak`

What happened:
Address is not recognized.

Expected result:
Address is recognized. zec-qt-wallet is launched (or brought in focus if already open) and the "Pay From" field in Send tab gets filled with the Zcash address.

Notes:
Feel free to test with my website http://www.dimitrisapostolou.com

**Comment by rex4539** [comment]
Bitcoin Core, Bitcoin ABC and Dash Core clients all utilize their respective URIs.

**Comment by garethtdavies** [comment]
Related: https://github.com/zcash/zcash/issues/2319

**Comment by wbobeirne** [comment]
Would love to see support for query parameters as well. `?amount=123&memo=456` should ideally be respected if provided.

**Comment by rex4539** [comment]
Any hope to get the expected URI behavior like in Bitcoin Core or Dash Core?

eg. clicking on a URI link: zec-qt-wallet is launched (or brought in focus if already open) and the "Pay From" field in Send tab gets filled with the Zcash address.

**Comment by rex4539** [comment]
Fixed in master.
