### ISSUE TITLE
Killing internet connection and reconnecting does not resume parameter download

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zecwallet#54]
Reproducibility: always

Prerequisites:
Clean user account that has never run zcashd before.

Steps:
1. Launch zec-qt-wallet
2. During the parameter download, kill your internet connection.
3. Restart your internet connection.

What happened:
Parameter download does not resume.

Expected result:
Parameter download resumes.

**Comment by adityapk00** [comment]
I'm going to close this as won't fix, since doing a restart in Qt turned out to be non-trivial. It just restarts the full download if the files are missing.
