### ISSUE TITLE
Add custom fee field to z-board app

### ISSUE THREAD

**Issue by the-metalworker** [ZcashFoundation/zecwallet#72]
There is no custom fee field in the "Post to z-board.net" app, while the main send app does allow the user to set a custom fee.

**Comment by adityapk00** [comment]
I've gotten feedback that having a custom fee itself is a bad idea from a privacy perspective, and we should not allow it. I put it in the transactions tab because a lot of people really want it. 

Putting it in the z-board app screen might be a bad idea, because then anyone could look at the blockchain and identify the Tx that posted to z-board, which beats the anonymous nature of the z-board.net app.

**Comment by the-metalworker** [comment]
> Putting it in the z-board app screen might be a bad idea, because then anyone could look at the blockchain and identify the Tx that posted to z-board, which beats the anonymous nature of the z-board.net app.

I'm not sure I understand this point. How does adding the custom fee to the z-board app screen make it possible to identify the tx that posted to z-board? Wouldn't the transaction just look like any other transaction that uses a custom fee? Further, isn't it already possible to tell which transaction added a message to z-board since everyone has the view key? (I'm not sure about this last point, just wondering.)

**Comment by adityapk00** [comment]
There's some info in this thread here: https://twitter.com/zooko/status/1062763961081315328 and https://twitter.com/lightcoin/status/1062782620982038528

Basically, a non-standard fee leaks meta-data, and an attacker can correlate it with all kinds of external info to make connections. 

The viewing-key point is a good one, I hadn't thought of that. Although note that even with a viewing key, you can't actually who posted the message.

**Comment by the-metalworker** [comment]
The best option seems to be to remove the custom fee option altogether then. (In which case this issue should be re-named "Remove custom fee option from send tab".)

**Comment by PRabahy** [comment]
I was one of the people that originally asked for a custom fee (https://github.com/ZcashFoundation/zec-qt-wallet/issues/48). The way that it was implemented still doesn't allow me to send with 0 fee which is what I actually wanted to do.

IMO, fees should be the result of a fee market, not a hardcoded number. If every piece of software has the same hardcoded fee, it will work fine as a spam prevention measure, but if/when the blocks get full everybody is going to scramble to figure out how to get their transaction out of the backlog.

**Comment by adityapk00** [comment]
Closing this issue, because setting custom fees is pretty privacy-violating.
