### ISSUE TITLE
Include more information about what exactly the "Turnstile Migration" app does

### ISSUE THREAD

**Issue by the-metalworker** [ZcashFoundation/zecwallet#73]
I want to be able to assess how well this works vs just doing the migration manually, and the app offers very little information about what exactly the turnstile app does. Information such as: What denominations does it use? How and why does it choose those denominations? And does the wallet need to be open the whole time? What happens if the wallet closes before the migration is complete?

**Comment by adityapk00** [comment]
Good idea. I'll make a wiki page and show it in the UI

**Comment by adityapk00** [comment]
Forgot to close this issue. Docs are here: https://electriccoin.co/blog/sprout-to-sapling-migration-tool/
