### ISSUE TITLE
Add option to download proving keys over Tor

### ISSUE THREAD

**Issue by the-metalworker** [ZcashFoundation/zecwallet#97]
I just installed zec-qt-wallet on a new machine and noticed that it did not ask me to connect over Tor before beginning to download the proving keys. Instead I was only presented with the option of connecting over Tor after the proving keys were downloaded. While not downloading the proving keys over Tor is certainly faster, for the privacy-minded user it would be nice to have the option to do this step over Tor, too.

**Comment by buzon7** [comment]
hi, did you see this guide? https://github.com/ZcashAnonymous/zcash-tor-manual

**Comment by the-metalworker** [comment]
Hi @buzon7 thank you for sharing. That seems to be a guide for if users who are running zcashd on a separate server, whereas I have zec-qt-wallet installed on my own laptop with Tor Browser running in the background. Since zec-qt-wallet can download the blockchain over Tor with this configuration it should be able to download the proving keys over Tor as well.

**Comment by adityapk00** [comment]
Duplicate #151
