### ISSUE TITLE
Improve documentation for remote node usage

### ISSUE THREAD

**Issue by the-metalworker** [ZcashFoundation/zecwallet#98]
I have a full node running on a small Linux server on my local network and would like to pair this node with zec-qt-wallet running on my laptop. I used the [remote node instructions](https://github.com/ZcashFoundation/zec-qt-wallet/wiki/Troubleshooting-&-FAQ#4-connecting-to-a-remote-zcashd) in the wiki to add the correct lines to the zcash conf file on my laptop, and after restarting the wallet I have a successful connection. 

A few comments that I think can help improve this documentation:

- I couldn't actually edit my remote node settings from Edit -> Settings as the documentation suggested. Instead I had to navigate to the zcash directory and open the conf file in Text Editor to modify it.
- Tell users what they need to add to the conf file for the wallet. I took a stab in the dark and added `host=127.0.0.1:8232`, saved the file, restarted the wallet, and thankfully I got it right on my first guess so it worked.
- I notice that the wallet seems to be controlling the wallet on the node rather than a new wallet created locally on my laptop i.e. I had some ZEC stored in the wallet on my remote node and I see it shows up in the zec-qt-wallet on my laptop. Is there a way to separate node and wallet functionality, to use my remote node to get blockchain data but have zec-qt-wallet store and use wallet data locally on my laptop? If so, it would be good to document how to do this. If not, it would be good to add documentation noting this fact so users are aware of this limitation.

**Comment by adityapk00** [comment]
In the docs: https://docs.zecwallet.co/using-zecwallet/#connecting-to-an-external-zcashd
