### ISSUE TITLE
Update the turnstile migration tool as per spec

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zecwallet#99]
See this [forum discussion](https://forum.zcashcommunity.com/t/zcash-counterfeiting-vulnerability-successfully-remediated/32671/44) and the [spec](https://github.com/zcash/zips/pull/197).

**Comment by adityapk00** [comment]
I assume this means that zcashd will have the new migrate RPC call, which zec-qt-wallet will use to do the turnstile migration. 

I'll wait for the new zcashd release, then incorporate it into zec-qt-wallet.

Leaving this open till then.

**Comment by rex4539** [comment]
The 2.0.5 release code has just been merged, so work on this can officially start :)

**Comment by adityapk00** [comment]
Included in 0.6.11
